-- ============================================================
-- 접지리플렛(PRD_000048)·와이드 접지리플렛(PRD_000049) 완전 견적 종단 적재본
--   생성기: gen_full.py · 권위 260702 · 라이브 차원행 참조만(신규 mint 0)
--   구성: L1 기초(공식·인쇄비·접지공정·사이즈) + 옵션레이어(인쇄/종이/코팅/후가공) + 접지 옵션그룹 + 코팅 제약
--   AMBIG 해소: 접지=공정축(049 동형). 048 공식 PRF_FOLD_SUM(스텁)→PRF_DGP_E 재바인딩
-- ============================================================
BEGIN;

-- ===== [L1] 접지리플렛(PRD_000048) 기초 =====
-- 공식 재바인딩: PRF_FOLD_SUM(접지비 카드 2단 단일=스텁) → PRF_DGP_E(디지털인쇄 원자합산형E 접지카드·접지리플렛)
UPDATE t_prd_product_price_formulas SET frm_cd='PRF_DGP_E',note='접지리플렛 동형 재바인딩(스텁 PRF_FOLD_SUM→접지리플렛 family PRF_DGP_E) 260703',upd_dt=now() WHERE prd_cd='PRD_000048';
-- 인쇄비 배선: 디지털인쇄 base 공정(mand) — 부재 시 인쇄비 영구 0
INSERT INTO t_prd_product_processes (prd_cd,proc_cd,mand_proc_yn,disp_seq,del_yn,reg_dt) VALUES ('PRD_000048','PROC_000004','Y',-1,'N',now()) ON CONFLICT (prd_cd,proc_cd) DO UPDATE SET mand_proc_yn=EXCLUDED.mand_proc_yn,disp_seq=EXCLUDED.disp_seq,del_yn='N',upd_dt=now();
-- 접지 공정: 반접지
INSERT INTO t_prd_product_processes (prd_cd,proc_cd,mand_proc_yn,disp_seq,del_yn,reg_dt) VALUES ('PRD_000048','PROC_000107','N',1,'N',now()) ON CONFLICT (prd_cd,proc_cd) DO UPDATE SET mand_proc_yn=EXCLUDED.mand_proc_yn,disp_seq=EXCLUDED.disp_seq,del_yn='N',upd_dt=now();
-- 접지 공정: 3단접지
INSERT INTO t_prd_product_processes (prd_cd,proc_cd,mand_proc_yn,disp_seq,del_yn,reg_dt) VALUES ('PRD_000048','PROC_000060','N',2,'N',now()) ON CONFLICT (prd_cd,proc_cd) DO UPDATE SET mand_proc_yn=EXCLUDED.mand_proc_yn,disp_seq=EXCLUDED.disp_seq,del_yn='N',upd_dt=now();
-- 접지 공정: 4단병풍접지
INSERT INTO t_prd_product_processes (prd_cd,proc_cd,mand_proc_yn,disp_seq,del_yn,reg_dt) VALUES ('PRD_000048','PROC_000071','N',3,'N',now()) ON CONFLICT (prd_cd,proc_cd) DO UPDATE SET mand_proc_yn=EXCLUDED.mand_proc_yn,disp_seq=EXCLUDED.disp_seq,del_yn='N',upd_dt=now();
-- 접지 공정: 4단대문접지
INSERT INTO t_prd_product_processes (prd_cd,proc_cd,mand_proc_yn,disp_seq,del_yn,reg_dt) VALUES ('PRD_000048','PROC_000106','N',4,'N',now()) ON CONFLICT (prd_cd,proc_cd) DO UPDATE SET mand_proc_yn=EXCLUDED.mand_proc_yn,disp_seq=EXCLUDED.disp_seq,del_yn='N',upd_dt=now();
-- 사이즈(A5/A4/A3) — 권위 재단사이즈 landscape = 라이브 siz_cd 정확 일치
-- A5 210x148
INSERT INTO t_prd_product_sizes (prd_cd,siz_cd,dflt_yn,disp_seq,min_qty,max_qty,qty_incr,del_yn,reg_dt) VALUES ('PRD_000048','SIZ_000049','Y',1,2,100000,1,'N',now()) ON CONFLICT (prd_cd,siz_cd) DO UPDATE SET dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,min_qty=EXCLUDED.min_qty,max_qty=EXCLUDED.max_qty,qty_incr=EXCLUDED.qty_incr,del_yn='N',upd_dt=now();
-- A4 297x210
INSERT INTO t_prd_product_sizes (prd_cd,siz_cd,dflt_yn,disp_seq,min_qty,max_qty,qty_incr,del_yn,reg_dt) VALUES ('PRD_000048','SIZ_000051','N',2,2,100000,1,'N',now()) ON CONFLICT (prd_cd,siz_cd) DO UPDATE SET dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,min_qty=EXCLUDED.min_qty,max_qty=EXCLUDED.max_qty,qty_incr=EXCLUDED.qty_incr,del_yn='N',upd_dt=now();
-- A3 420x297
INSERT INTO t_prd_product_sizes (prd_cd,siz_cd,dflt_yn,disp_seq,min_qty,max_qty,qty_incr,del_yn,reg_dt) VALUES ('PRD_000048','SIZ_000054','N',3,2,100000,1,'N',now()) ON CONFLICT (prd_cd,siz_cd) DO UPDATE SET dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,min_qty=EXCLUDED.min_qty,max_qty=EXCLUDED.max_qty,qty_incr=EXCLUDED.qty_incr,del_yn='N',upd_dt=now();

-- ===== [L1] 와이드 접지리플렛(PRD_000049) 기초 =====
-- 공식 PRF_DGP_E 이미 바인딩(변경 없음) · 사이즈 SIZ_000055(3절) 이미 적재
-- 접지 공정 보강: 4단대문접지(권위 있으나 라이브 부재)
INSERT INTO t_prd_product_processes (prd_cd,proc_cd,mand_proc_yn,disp_seq,del_yn,reg_dt) VALUES ('PRD_000049','PROC_000106','N',2,'N',now()) ON CONFLICT (prd_cd,proc_cd) DO UPDATE SET mand_proc_yn=EXCLUDED.mand_proc_yn,disp_seq=EXCLUDED.disp_seq,del_yn='N',upd_dt=now();

-- ===== [L2] 옵션 레이어(인쇄·종이·코팅·후가공) + 코팅×두께 제약 =====
-- ===== 접지리플렛 (PRD_000048) =====
-- option_groups
INSERT INTO t_prd_product_option_groups (prd_cd,opt_grp_cd,opt_grp_nm,sel_typ_cd,min_sel_cnt,max_sel_cnt,mand_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPT_000147','인쇄','SEL_TYPE.01',1,1,'Y',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_grp_cd) DO UPDATE SET opt_grp_nm=EXCLUDED.opt_grp_nm,sel_typ_cd=EXCLUDED.sel_typ_cd,min_sel_cnt=EXCLUDED.min_sel_cnt,max_sel_cnt=EXCLUDED.max_sel_cnt,mand_yn=EXCLUDED.mand_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_groups (prd_cd,opt_grp_cd,opt_grp_nm,sel_typ_cd,min_sel_cnt,max_sel_cnt,mand_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPT_000148','종이','SEL_TYPE.01',1,1,'Y',2,'Y','N',now()) ON CONFLICT (prd_cd,opt_grp_cd) DO UPDATE SET opt_grp_nm=EXCLUDED.opt_grp_nm,sel_typ_cd=EXCLUDED.sel_typ_cd,min_sel_cnt=EXCLUDED.min_sel_cnt,max_sel_cnt=EXCLUDED.max_sel_cnt,mand_yn=EXCLUDED.mand_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_groups (prd_cd,opt_grp_cd,opt_grp_nm,sel_typ_cd,min_sel_cnt,max_sel_cnt,mand_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPT_000149','코팅','SEL_TYPE.01',0,1,'N',3,'Y','N',now()) ON CONFLICT (prd_cd,opt_grp_cd) DO UPDATE SET opt_grp_nm=EXCLUDED.opt_grp_nm,sel_typ_cd=EXCLUDED.sel_typ_cd,min_sel_cnt=EXCLUDED.min_sel_cnt,max_sel_cnt=EXCLUDED.max_sel_cnt,mand_yn=EXCLUDED.mand_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_groups (prd_cd,opt_grp_cd,opt_grp_nm,sel_typ_cd,min_sel_cnt,max_sel_cnt,mand_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPT_000150','후가공','SEL_TYPE.02',0,2,'N',4,'Y','N',now()) ON CONFLICT (prd_cd,opt_grp_cd) DO UPDATE SET opt_grp_nm=EXCLUDED.opt_grp_nm,sel_typ_cd=EXCLUDED.sel_typ_cd,min_sel_cnt=EXCLUDED.min_sel_cnt,max_sel_cnt=EXCLUDED.max_sel_cnt,mand_yn=EXCLUDED.mand_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
-- options
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000556','OPT_000147','양면','Y',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000557','OPT_000148','백색모조지 100g','Y',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000558','OPT_000148','백색모조지 120g','N',2,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000559','OPT_000148','백색모조지 220g','N',3,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000560','OPT_000148','아트지 100g','N',4,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000561','OPT_000148','아트지 120g','N',5,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000562','OPT_000148','아트지 150g','N',6,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000563','OPT_000148','아트지 180g','N',7,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000564','OPT_000148','아트지 200g','N',8,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000565','OPT_000148','아트지 250g','N',9,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000566','OPT_000148','아트지 300g','N',10,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000567','OPT_000148','스노우지 100g','N',11,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000568','OPT_000148','스노우지 120g','N',12,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000569','OPT_000148','스노우지 150g','N',13,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000570','OPT_000148','스노우지 180g','N',14,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000571','OPT_000148','스노우지 200g','N',15,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000572','OPT_000148','스노우지 250g','N',16,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000573','OPT_000148','스노우지 300g','N',17,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000574','OPT_000148','앙상블 100g','N',18,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000575','OPT_000148','앙상블 130g','N',19,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000576','OPT_000148','앙상블 160g','N',20,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000577','OPT_000148','앙상블 190g','N',21,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000578','OPT_000148','앙상블 210g','N',22,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000579','OPT_000148','랑데뷰 WH 240g','N',23,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000580','OPT_000148','랑데뷰 WH 310g','N',24,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000581','OPT_000148','몽블랑 100g','N',25,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000582','OPT_000148','몽블랑 130g','N',26,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000583','OPT_000148','몽블랑 160g','N',27,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000584','OPT_000148','몽블랑 190g','N',28,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000585','OPT_000148','몽블랑 210g','N',29,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000586','OPT_000148','몽블랑 240g','N',30,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000587','OPT_000148','아코팩','N',31,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000588','OPT_000148','리사이클러스','N',32,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000589','OPT_000148','매쉬멜로우','N',33,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000590','OPT_000148','린넨커버','N',34,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000591','OPT_000148','스타화이트','N',35,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000592','OPT_000148','클래식 크래스트','N',36,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000593','OPT_000148','리브스디자인 250g','N',37,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000594','OPT_000148','매직터치','N',38,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000595','OPT_000148','켄도','N',39,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000596','OPT_000148','띤또레또 200g','N',40,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000597','OPT_000148','띤또레또 250g','N',41,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000598','OPT_000148','한지','N',42,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000599','OPT_000148','스코트랜드','N',43,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000600','OPT_000148','스타드림','N',44,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000601','OPT_000149','코팅없음','Y',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000602','OPT_000149','유광','N',2,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000603','OPT_000149','무광','N',3,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000604','OPT_000150','가변텍스트','N',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000605','OPT_000150','가변이미지','N',2,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
-- option_items
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000556',1,'OPT_REF_DIM.06','1',NULL,1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000557',1,'OPT_REF_DIM.03','MAT_000072','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000558',1,'OPT_REF_DIM.03','MAT_000073','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000559',1,'OPT_REF_DIM.03','MAT_000074','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000560',1,'OPT_REF_DIM.03','MAT_000076','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000561',1,'OPT_REF_DIM.03','MAT_000077','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000562',1,'OPT_REF_DIM.03','MAT_000078','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000563',1,'OPT_REF_DIM.03','MAT_000079','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000564',1,'OPT_REF_DIM.03','MAT_000080','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000565',1,'OPT_REF_DIM.03','MAT_000081','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000566',1,'OPT_REF_DIM.03','MAT_000082','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000567',1,'OPT_REF_DIM.03','MAT_000086','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000568',1,'OPT_REF_DIM.03','MAT_000087','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000569',1,'OPT_REF_DIM.03','MAT_000088','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000570',1,'OPT_REF_DIM.03','MAT_000089','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000571',1,'OPT_REF_DIM.03','MAT_000090','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000572',1,'OPT_REF_DIM.03','MAT_000091','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000573',1,'OPT_REF_DIM.03','MAT_000092','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000574',1,'OPT_REF_DIM.03','MAT_000095','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000575',1,'OPT_REF_DIM.03','MAT_000096','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000576',1,'OPT_REF_DIM.03','MAT_000097','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000577',1,'OPT_REF_DIM.03','MAT_000098','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000578',1,'OPT_REF_DIM.03','MAT_000099','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000579',1,'OPT_REF_DIM.03','MAT_000101','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000580',1,'OPT_REF_DIM.03','MAT_000102','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000581',1,'OPT_REF_DIM.03','MAT_000104','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000582',1,'OPT_REF_DIM.03','MAT_000105','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000583',1,'OPT_REF_DIM.03','MAT_000106','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000584',1,'OPT_REF_DIM.03','MAT_000107','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000585',1,'OPT_REF_DIM.03','MAT_000108','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000586',1,'OPT_REF_DIM.03','MAT_000109','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000587',1,'OPT_REF_DIM.03','MAT_000113','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000588',1,'OPT_REF_DIM.03','MAT_000114','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000589',1,'OPT_REF_DIM.03','MAT_000115','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000590',1,'OPT_REF_DIM.03','MAT_000116','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000591',1,'OPT_REF_DIM.03','MAT_000117','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000592',1,'OPT_REF_DIM.03','MAT_000118','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000593',1,'OPT_REF_DIM.03','MAT_000119','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000594',1,'OPT_REF_DIM.03','MAT_000120','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000595',1,'OPT_REF_DIM.03','MAT_000121','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000596',1,'OPT_REF_DIM.03','MAT_000123','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000597',1,'OPT_REF_DIM.03','MAT_000124','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000598',1,'OPT_REF_DIM.03','MAT_000125','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000599',1,'OPT_REF_DIM.03','MAT_000126','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000600',1,'OPT_REF_DIM.03','MAT_000127','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000602',1,'OPT_REF_DIM.04','PROC_000014',NULL,1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000603',1,'OPT_REF_DIM.04','PROC_000015',NULL,1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000604',1,'OPT_REF_DIM.04','PROC_000031',NULL,1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000605',1,'OPT_REF_DIM.04','PROC_000032',NULL,1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
-- constraint: R_EXCL_COATING_THIN_PAPER
INSERT INTO t_prd_product_constraints (prd_cd,rule_cd,rule_nm,rule_typ_cd,logic,err_msg,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','R_EXCL_COATING_THIN_PAPER','[제약조건] 코팅은 두꺼운 종이(180g 이상)에서만 가능','RULE_TYPE.02','{"!":{"and":[{"or":[{"in":["OPV_000602",{"var":"sel_opts"}]},{"in":["OPV_000603",{"var":"sel_opts"}]}]},{"or":[{"===":[{"var":"mat_cd__usage_cd"},"MAT_000072__USAGE.07"]},{"===":[{"var":"mat_cd__usage_cd"},"MAT_000073__USAGE.07"]},{"===":[{"var":"mat_cd__usage_cd"},"MAT_000076__USAGE.07"]},{"===":[{"var":"mat_cd__usage_cd"},"MAT_000077__USAGE.07"]},{"===":[{"var":"mat_cd__usage_cd"},"MAT_000078__USAGE.07"]},{"===":[{"var":"mat_cd__usage_cd"},"MAT_000086__USAGE.07"]},{"===":[{"var":"mat_cd__usage_cd"},"MAT_000087__USAGE.07"]},{"===":[{"var":"mat_cd__usage_cd"},"MAT_000088__USAGE.07"]},{"===":[{"var":"mat_cd__usage_cd"},"MAT_000095__USAGE.07"]},{"===":[{"var":"mat_cd__usage_cd"},"MAT_000096__USAGE.07"]},{"===":[{"var":"mat_cd__usage_cd"},"MAT_000097__USAGE.07"]},{"===":[{"var":"mat_cd__usage_cd"},"MAT_000104__USAGE.07"]},{"===":[{"var":"mat_cd__usage_cd"},"MAT_000105__USAGE.07"]},{"===":[{"var":"mat_cd__usage_cd"},"MAT_000106__USAGE.07"]},{"===":[{"var":"mat_cd__usage_cd"},"MAT_000125__USAGE.07"]}]}]}}'::jsonb,'코팅은 두꺼운 종이(180g 이상)에서만 가능합니다. 종이를 180g 이상으로 바꾸거나 코팅을 빼 주세요.','Y','N',now()) ON CONFLICT (prd_cd,rule_cd) DO UPDATE SET rule_nm=EXCLUDED.rule_nm,rule_typ_cd=EXCLUDED.rule_typ_cd,logic=EXCLUDED.logic,err_msg=EXCLUDED.err_msg,use_yn='Y',del_yn='N',upd_dt=now();

-- ===== 와이드 접지리플렛 (PRD_000049) =====
-- option_groups
INSERT INTO t_prd_product_option_groups (prd_cd,opt_grp_cd,opt_grp_nm,sel_typ_cd,min_sel_cnt,max_sel_cnt,mand_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000049','OPT_000151','인쇄','SEL_TYPE.01',1,1,'Y',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_grp_cd) DO UPDATE SET opt_grp_nm=EXCLUDED.opt_grp_nm,sel_typ_cd=EXCLUDED.sel_typ_cd,min_sel_cnt=EXCLUDED.min_sel_cnt,max_sel_cnt=EXCLUDED.max_sel_cnt,mand_yn=EXCLUDED.mand_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_groups (prd_cd,opt_grp_cd,opt_grp_nm,sel_typ_cd,min_sel_cnt,max_sel_cnt,mand_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000049','OPT_000152','종이','SEL_TYPE.01',1,1,'Y',2,'Y','N',now()) ON CONFLICT (prd_cd,opt_grp_cd) DO UPDATE SET opt_grp_nm=EXCLUDED.opt_grp_nm,sel_typ_cd=EXCLUDED.sel_typ_cd,min_sel_cnt=EXCLUDED.min_sel_cnt,max_sel_cnt=EXCLUDED.max_sel_cnt,mand_yn=EXCLUDED.mand_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_groups (prd_cd,opt_grp_cd,opt_grp_nm,sel_typ_cd,min_sel_cnt,max_sel_cnt,mand_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000049','OPT_000153','코팅','SEL_TYPE.01',0,1,'N',3,'Y','N',now()) ON CONFLICT (prd_cd,opt_grp_cd) DO UPDATE SET opt_grp_nm=EXCLUDED.opt_grp_nm,sel_typ_cd=EXCLUDED.sel_typ_cd,min_sel_cnt=EXCLUDED.min_sel_cnt,max_sel_cnt=EXCLUDED.max_sel_cnt,mand_yn=EXCLUDED.mand_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_groups (prd_cd,opt_grp_cd,opt_grp_nm,sel_typ_cd,min_sel_cnt,max_sel_cnt,mand_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000049','OPT_000154','후가공','SEL_TYPE.02',0,2,'N',4,'Y','N',now()) ON CONFLICT (prd_cd,opt_grp_cd) DO UPDATE SET opt_grp_nm=EXCLUDED.opt_grp_nm,sel_typ_cd=EXCLUDED.sel_typ_cd,min_sel_cnt=EXCLUDED.min_sel_cnt,max_sel_cnt=EXCLUDED.max_sel_cnt,mand_yn=EXCLUDED.mand_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
-- options
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000049','OPV_000606','OPT_000151','양면','Y',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000049','OPV_000607','OPT_000152','아트지 150g (3절)','Y',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000049','OPV_000608','OPT_000152','스노우지 250g (3절)','N',2,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000049','OPV_000609','OPT_000152','몽블랑 130g (3절)','N',3,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000049','OPV_000610','OPT_000152','몽블랑 190g (3절)','N',4,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000049','OPV_000611','OPT_000152','몽블랑 240g (3절)','N',5,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000049','OPV_000612','OPT_000153','코팅없음','Y',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000049','OPV_000613','OPT_000153','유광','N',2,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000049','OPV_000614','OPT_000153','무광','N',3,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000049','OPV_000615','OPT_000154','가변텍스트','N',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000049','OPV_000616','OPT_000154','가변이미지','N',2,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
-- option_items
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000049','OPV_000606',1,'OPT_REF_DIM.06','1',NULL,1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000049','OPV_000607',1,'OPT_REF_DIM.03','MAT_000083','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000049','OPV_000608',1,'OPT_REF_DIM.03','MAT_000093','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000049','OPV_000609',1,'OPT_REF_DIM.03','MAT_000110','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000049','OPV_000610',1,'OPT_REF_DIM.03','MAT_000111','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000049','OPV_000611',1,'OPT_REF_DIM.03','MAT_000112','USAGE.07',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000049','OPV_000613',1,'OPT_REF_DIM.04','PROC_000014',NULL,1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000049','OPV_000614',1,'OPT_REF_DIM.04','PROC_000015',NULL,1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000049','OPV_000615',1,'OPT_REF_DIM.04','PROC_000031',NULL,1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000049','OPV_000616',1,'OPT_REF_DIM.04','PROC_000032',NULL,1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
-- constraint: R_EXCL_COATING_THIN_PAPER
INSERT INTO t_prd_product_constraints (prd_cd,rule_cd,rule_nm,rule_typ_cd,logic,err_msg,use_yn,del_yn,reg_dt) VALUES ('PRD_000049','R_EXCL_COATING_THIN_PAPER','[제약조건] 코팅은 두꺼운 종이(180g 이상)에서만 가능','RULE_TYPE.02','{"!":{"and":[{"or":[{"in":["OPV_000613",{"var":"sel_opts"}]},{"in":["OPV_000614",{"var":"sel_opts"}]}]},{"or":[{"===":[{"var":"mat_cd__usage_cd"},"MAT_000083__USAGE.07"]},{"===":[{"var":"mat_cd__usage_cd"},"MAT_000110__USAGE.07"]}]}]}}'::jsonb,'코팅은 두꺼운 종이(180g 이상)에서만 가능합니다. 종이를 180g 이상으로 바꾸거나 코팅을 빼 주세요.','Y','N',now()) ON CONFLICT (prd_cd,rule_cd) DO UPDATE SET rule_nm=EXCLUDED.rule_nm,rule_typ_cd=EXCLUDED.rule_typ_cd,logic=EXCLUDED.logic,err_msg=EXCLUDED.err_msg,use_yn='Y',del_yn='N',upd_dt=now();


-- ===== [L2] 접지 옵션그룹(택1·필수) — 접지 공정 UI 선택 =====
-- 접지 옵션그룹 (PRD_000048)
INSERT INTO t_prd_product_option_groups (prd_cd,opt_grp_cd,opt_grp_nm,sel_typ_cd,min_sel_cnt,max_sel_cnt,mand_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPT_000155','접지','SEL_TYPE.01',1,1,'Y',5,'Y','N',now()) ON CONFLICT (prd_cd,opt_grp_cd) DO UPDATE SET opt_grp_nm=EXCLUDED.opt_grp_nm,sel_typ_cd=EXCLUDED.sel_typ_cd,min_sel_cnt=EXCLUDED.min_sel_cnt,max_sel_cnt=EXCLUDED.max_sel_cnt,mand_yn=EXCLUDED.mand_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000617','OPT_000155','반접지','Y',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000617',1,'OPT_REF_DIM.04','PROC_000107',NULL,1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000618','OPT_000155','3단접지','N',2,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000618',1,'OPT_REF_DIM.04','PROC_000060',NULL,1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000619','OPT_000155','4단병풍접지','N',3,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000619',1,'OPT_REF_DIM.04','PROC_000071',NULL,1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000620','OPT_000155','4단대문접지','N',4,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000048','OPV_000620',1,'OPT_REF_DIM.04','PROC_000106',NULL,1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
-- 접지 옵션그룹 (PRD_000049)
INSERT INTO t_prd_product_option_groups (prd_cd,opt_grp_cd,opt_grp_nm,sel_typ_cd,min_sel_cnt,max_sel_cnt,mand_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000049','OPT_000156','접지','SEL_TYPE.01',1,1,'Y',5,'Y','N',now()) ON CONFLICT (prd_cd,opt_grp_cd) DO UPDATE SET opt_grp_nm=EXCLUDED.opt_grp_nm,sel_typ_cd=EXCLUDED.sel_typ_cd,min_sel_cnt=EXCLUDED.min_sel_cnt,max_sel_cnt=EXCLUDED.max_sel_cnt,mand_yn=EXCLUDED.mand_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000049','OPV_000621','OPT_000156','3단접지','Y',1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000049','OPV_000621',1,'OPT_REF_DIM.04','PROC_000060',NULL,1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000049','OPV_000622','OPT_000156','4단병풍접지','N',2,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000049','OPV_000622',1,'OPT_REF_DIM.04','PROC_000071',NULL,1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_options (prd_cd,opt_cd,opt_grp_cd,opt_nm,dflt_yn,disp_seq,use_yn,del_yn,reg_dt) VALUES ('PRD_000049','OPV_000623','OPT_000156','4단대문접지','N',3,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd) DO UPDATE SET opt_grp_cd=EXCLUDED.opt_grp_cd,opt_nm=EXCLUDED.opt_nm,dflt_yn=EXCLUDED.dflt_yn,disp_seq=EXCLUDED.disp_seq,use_yn='Y',del_yn='N',upd_dt=now();
INSERT INTO t_prd_product_option_items (prd_cd,opt_cd,item_seq,ref_dim_cd,ref_key1,ref_key2,qty,use_yn,del_yn,reg_dt) VALUES ('PRD_000049','OPV_000623',1,'OPT_REF_DIM.04','PROC_000106',NULL,1,'Y','N',now()) ON CONFLICT (prd_cd,opt_cd,item_seq) DO UPDATE SET ref_dim_cd=EXCLUDED.ref_dim_cd,ref_key1=EXCLUDED.ref_key1,ref_key2=EXCLUDED.ref_key2,qty=EXCLUDED.qty,use_yn='Y',del_yn='N',upd_dt=now();

COMMIT;
