-- 판걸이수 권위 적재 (forward 게이지손실 확정분) — 2026-07-01
-- basis: 시트 작업사이즈 == 라이브 work 확인분만. reverse(시트>엔진)·썬캡·투명 제외.
BEGIN;
INSERT INTO t_siz_pansu (prd_cd,plt_siz_cd,item_siz_cd,pansu,src,note) VALUES (NULL,'SIZ_000499','SIZ_000003',8,'판걸이수시트','100x150 엽서 / 엽서북내지 (기하9→시트8)') ON CONFLICT (plt_siz_cd,item_siz_cd,COALESCE(prd_cd,'')) DO UPDATE SET pansu=EXCLUDED.pansu,src=EXCLUDED.src,note=EXCLUDED.note;
INSERT INTO t_siz_pansu (prd_cd,plt_siz_cd,item_siz_cd,pansu,src,note) VALUES (NULL,'SIZ_000499','SIZ_000009',21,'판걸이수시트','90x55 명함 (기하24→시트21)') ON CONFLICT (plt_siz_cd,item_siz_cd,COALESCE(prd_cd,'')) DO UPDATE SET pansu=EXCLUDED.pansu,src=EXCLUDED.src,note=EXCLUDED.note;
INSERT INTO t_siz_pansu (prd_cd,plt_siz_cd,item_siz_cd,pansu,src,note) VALUES (NULL,'SIZ_000499','SIZ_000010',21,'판걸이수시트','86x55 명함 (기하25→시트21)') ON CONFLICT (plt_siz_cd,item_siz_cd,COALESCE(prd_cd,'')) DO UPDATE SET pansu=EXCLUDED.pansu,src=EXCLUDED.src,note=EXCLUDED.note;
INSERT INTO t_siz_pansu (prd_cd,plt_siz_cd,item_siz_cd,pansu,src,note) VALUES (NULL,'SIZ_000499','SIZ_000012',21,'판걸이수시트','55x86 포토카드 (기하25→시트21)') ON CONFLICT (plt_siz_cd,item_siz_cd,COALESCE(prd_cd,'')) DO UPDATE SET pansu=EXCLUDED.pansu,src=EXCLUDED.src,note=EXCLUDED.note;
INSERT INTO t_siz_pansu (prd_cd,plt_siz_cd,item_siz_cd,pansu,src,note) VALUES (NULL,'SIZ_000499','SIZ_000029',1,'판걸이수시트','403x135 3단접지카드 (기하2→시트1)') ON CONFLICT (plt_siz_cd,item_siz_cd,COALESCE(prd_cd,'')) DO UPDATE SET pansu=EXCLUDED.pansu,src=EXCLUDED.src,note=EXCLUDED.note;
INSERT INTO t_siz_pansu (prd_cd,plt_siz_cd,item_siz_cd,pansu,src,note) VALUES (NULL,'SIZ_000499','SIZ_000030',1,'판걸이수시트','135x403 3단접지카드 (기하2→시트1)') ON CONFLICT (plt_siz_cd,item_siz_cd,COALESCE(prd_cd,'')) DO UPDATE SET pansu=EXCLUDED.pansu,src=EXCLUDED.src,note=EXCLUDED.note;
INSERT INTO t_siz_pansu (prd_cd,plt_siz_cd,item_siz_cd,pansu,src,note) VALUES (NULL,'SIZ_000499','SIZ_000034',9,'판걸이수시트','76x120 인쇄배경지 (기하10→시트9)') ON CONFLICT (plt_siz_cd,item_siz_cd,COALESCE(prd_cd,'')) DO UPDATE SET pansu=EXCLUDED.pansu,src=EXCLUDED.src,note=EXCLUDED.note;
INSERT INTO t_siz_pansu (prd_cd,plt_siz_cd,item_siz_cd,pansu,src,note) VALUES (NULL,'SIZ_000499','SIZ_000035',9,'판걸이수시트','86x120 인쇄배경지 (기하10→시트9)') ON CONFLICT (plt_siz_cd,item_siz_cd,COALESCE(prd_cd,'')) DO UPDATE SET pansu=EXCLUDED.pansu,src=EXCLUDED.src,note=EXCLUDED.note;
INSERT INTO t_siz_pansu (prd_cd,plt_siz_cd,item_siz_cd,pansu,src,note) VALUES (NULL,'SIZ_000499','SIZ_000047',24,'판걸이수시트','40x80 라벨택 (기하30→시트24)') ON CONFLICT (plt_siz_cd,item_siz_cd,COALESCE(prd_cd,'')) DO UPDATE SET pansu=EXCLUDED.pansu,src=EXCLUDED.src,note=EXCLUDED.note;
INSERT INTO t_siz_pansu (prd_cd,plt_siz_cd,item_siz_cd,pansu,src,note) VALUES (NULL,'SIZ_000499','SIZ_000048',24,'판걸이수시트','25x110 라벨택 (기하26→시트24)') ON CONFLICT (plt_siz_cd,item_siz_cd,COALESCE(prd_cd,'')) DO UPDATE SET pansu=EXCLUDED.pansu,src=EXCLUDED.src,note=EXCLUDED.note;
INSERT INTO t_siz_pansu (prd_cd,plt_siz_cd,item_siz_cd,pansu,src,note) VALUES (NULL,'SIZ_000499','SIZ_000071',12,'판걸이수시트','148 x 60 미니탁상형캘린더 (기하14→시트12)') ON CONFLICT (plt_siz_cd,item_siz_cd,COALESCE(prd_cd,'')) DO UPDATE SET pansu=EXCLUDED.pansu,src=EXCLUDED.src,note=EXCLUDED.note;
COMMIT;
