-- =====================================================================
-- step 12 — UPDATE t_prd_products.constraint_json (compile 캐시: 활성 3 rule AND)
-- 멱등: constraint_json IS DISTINCT FROM 새 값일 때만 UPDATE (동일하면 0행·재실행 delta 0).
-- compile = §5 AND(R-MAXN, R-PARAM, R-QTY-PANSU). jsonb. POD json-logic-js · 백엔드 json-logic-py 동일 평가.
-- =====================================================================
UPDATE t_prd_products
SET constraint_json = '{ "and": [ { "<=": [ { "reduce": [ { "var": "hugagong" }, { "+": [ { "var": "accumulator" }, 1 ] }, 0 ] }, 4 ] }, { "and": [ { ">=": [ { "var": "osi_julsu" }, 0 ] }, { "<=": [ { "var": "osi_julsu" }, 3 ] }, { ">=": [ { "var": "mising_julsu" }, 0 ] }, { "<=": [ { "var": "mising_julsu" }, 3 ] }, { ">=": [ { "var": "vartext_cnt" }, 0 ] }, { "<=": [ { "var": "vartext_cnt" }, 3 ] }, { ">=": [ { "var": "varimg_cnt" }, 0 ] }, { "<=": [ { "var": "varimg_cnt" }, 3 ] } ] }, { "or": [ { "and": [ { "==": [ { "var": "siz_cd" }, "SIZ_000001" ] }, { "==": [ { "%": [ { "var": "qty" }, 15 ] }, 0 ] } ] }, { "and": [ { "==": [ { "var": "siz_cd" }, "SIZ_000002" ] }, { "==": [ { "%": [ { "var": "qty" }, 12 ] }, 0 ] } ] }, { "and": [ { "==": [ { "var": "siz_cd" }, "SIZ_000003" ] }, { "==": [ { "%": [ { "var": "qty" }, 8 ] }, 0 ] } ] }, { "and": [ { "==": [ { "var": "siz_cd" }, "SIZ_000004" ] }, { "==": [ { "%": [ { "var": "qty" }, 6 ] }, 0 ] } ] }, { "and": [ { "==": [ { "var": "siz_cd" }, "SIZ_000005" ] }, { "==": [ { "%": [ { "var": "qty" }, 6 ] }, 0 ] } ] }, { "and": [ { "==": [ { "var": "siz_cd" }, "SIZ_000006" ] }, { "==": [ { "%": [ { "var": "qty" }, 4 ] }, 0 ] } ] }, { "and": [ { "==": [ { "var": "siz_cd" }, "SIZ_000007" ] }, { "==": [ { "%": [ { "var": "qty" }, 4 ] }, 0 ] } ] } ] } ] }'::jsonb
WHERE prd_cd = 'PRD_000016'
  AND constraint_json IS DISTINCT FROM '{ "and": [ { "<=": [ { "reduce": [ { "var": "hugagong" }, { "+": [ { "var": "accumulator" }, 1 ] }, 0 ] }, 4 ] }, { "and": [ { ">=": [ { "var": "osi_julsu" }, 0 ] }, { "<=": [ { "var": "osi_julsu" }, 3 ] }, { ">=": [ { "var": "mising_julsu" }, 0 ] }, { "<=": [ { "var": "mising_julsu" }, 3 ] }, { ">=": [ { "var": "vartext_cnt" }, 0 ] }, { "<=": [ { "var": "vartext_cnt" }, 3 ] }, { ">=": [ { "var": "varimg_cnt" }, 0 ] }, { "<=": [ { "var": "varimg_cnt" }, 3 ] } ] }, { "or": [ { "and": [ { "==": [ { "var": "siz_cd" }, "SIZ_000001" ] }, { "==": [ { "%": [ { "var": "qty" }, 15 ] }, 0 ] } ] }, { "and": [ { "==": [ { "var": "siz_cd" }, "SIZ_000002" ] }, { "==": [ { "%": [ { "var": "qty" }, 12 ] }, 0 ] } ] }, { "and": [ { "==": [ { "var": "siz_cd" }, "SIZ_000003" ] }, { "==": [ { "%": [ { "var": "qty" }, 8 ] }, 0 ] } ] }, { "and": [ { "==": [ { "var": "siz_cd" }, "SIZ_000004" ] }, { "==": [ { "%": [ { "var": "qty" }, 6 ] }, 0 ] } ] }, { "and": [ { "==": [ { "var": "siz_cd" }, "SIZ_000005" ] }, { "==": [ { "%": [ { "var": "qty" }, 6 ] }, 0 ] } ] }, { "and": [ { "==": [ { "var": "siz_cd" }, "SIZ_000006" ] }, { "==": [ { "%": [ { "var": "qty" }, 4 ] }, 0 ] } ] }, { "and": [ { "==": [ { "var": "siz_cd" }, "SIZ_000007" ] }, { "==": [ { "%": [ { "var": "qty" }, 4 ] }, 0 ] } ] } ] } ] }'::jsonb;
