-- 스티커/문구/봉투 판형 교정 UNDO
\set ON_ERROR_STOP on
BEGIN;
DELETE FROM t_prd_product_plate_sizes WHERE prd_cd IN ('PRD_000066','PRD_000067','PRD_000055','PRD_000056','PRD_000057','PRD_000179','PRD_000176','PRD_000181','PRD_000177','PRD_000178','PRD_000172','PRD_000173','PRD_000050');
INSERT INTO t_prd_product_plate_sizes (prd_cd,siz_cd,item_siz_cd,output_paper_typ_cd,output_file_typ,dflt_plt_yn,del_yn,reg_dt) VALUES ('PRD_000050','SIZ_000191','',NULL,'AI','Y','N',now());
INSERT INTO t_prd_product_plate_sizes (prd_cd,siz_cd,item_siz_cd,output_paper_typ_cd,output_file_typ,dflt_plt_yn,del_yn,reg_dt) VALUES ('PRD_000050','SIZ_000192','',NULL,NULL,'Y','N',now());
INSERT INTO t_prd_product_plate_sizes (prd_cd,siz_cd,item_siz_cd,output_paper_typ_cd,output_file_typ,dflt_plt_yn,del_yn,reg_dt) VALUES ('PRD_000050','SIZ_000193','',NULL,NULL,'Y','N',now());
INSERT INTO t_prd_product_plate_sizes (prd_cd,siz_cd,item_siz_cd,output_paper_typ_cd,output_file_typ,dflt_plt_yn,del_yn,reg_dt) VALUES ('PRD_000050','SIZ_000194','',NULL,NULL,'Y','N',now());
INSERT INTO t_prd_product_plate_sizes (prd_cd,siz_cd,item_siz_cd,output_paper_typ_cd,output_file_typ,dflt_plt_yn,del_yn,reg_dt) VALUES ('PRD_000055','SIZ_000050','','OUTPUT_PAPER_TYPE.03',NULL,'Y','N',now());
INSERT INTO t_prd_product_plate_sizes (prd_cd,siz_cd,item_siz_cd,output_paper_typ_cd,output_file_typ,dflt_plt_yn,del_yn,reg_dt) VALUES ('PRD_000055','SIZ_000052','','OUTPUT_PAPER_TYPE.03',NULL,'Y','N',now());
INSERT INTO t_prd_product_plate_sizes (prd_cd,siz_cd,item_siz_cd,output_paper_typ_cd,output_file_typ,dflt_plt_yn,del_yn,reg_dt) VALUES ('PRD_000055','SIZ_000198','','OUTPUT_PAPER_TYPE.03',NULL,'Y','N',now());
INSERT INTO t_prd_product_plate_sizes (prd_cd,siz_cd,item_siz_cd,output_paper_typ_cd,output_file_typ,dflt_plt_yn,del_yn,reg_dt) VALUES ('PRD_000056','SIZ_000050','','OUTPUT_PAPER_TYPE.03','PDF(W)','Y','N',now());
INSERT INTO t_prd_product_plate_sizes (prd_cd,siz_cd,item_siz_cd,output_paper_typ_cd,output_file_typ,dflt_plt_yn,del_yn,reg_dt) VALUES ('PRD_000056','SIZ_000052','','OUTPUT_PAPER_TYPE.03','AI (칼선)','Y','N',now());
INSERT INTO t_prd_product_plate_sizes (prd_cd,siz_cd,item_siz_cd,output_paper_typ_cd,output_file_typ,dflt_plt_yn,del_yn,reg_dt) VALUES ('PRD_000056','SIZ_000198','','OUTPUT_PAPER_TYPE.03','*아이마크','Y','N',now());
INSERT INTO t_prd_product_plate_sizes (prd_cd,siz_cd,item_siz_cd,output_paper_typ_cd,output_file_typ,dflt_plt_yn,del_yn,reg_dt) VALUES ('PRD_000057','SIZ_000199','','OUTPUT_PAPER_TYPE.03','PDF','Y','N',now());
INSERT INTO t_prd_product_plate_sizes (prd_cd,siz_cd,item_siz_cd,output_paper_typ_cd,output_file_typ,dflt_plt_yn,del_yn,reg_dt) VALUES ('PRD_000066','SIZ_000017','',NULL,NULL,'Y','N',now());
INSERT INTO t_prd_product_plate_sizes (prd_cd,siz_cd,item_siz_cd,output_paper_typ_cd,output_file_typ,dflt_plt_yn,del_yn,reg_dt) VALUES ('PRD_000066','SIZ_000065','',NULL,NULL,'Y','N',now());
INSERT INTO t_prd_product_plate_sizes (prd_cd,siz_cd,item_siz_cd,output_paper_typ_cd,output_file_typ,dflt_plt_yn,del_yn,reg_dt) VALUES ('PRD_000066','SIZ_000113','',NULL,NULL,'Y','N',now());
INSERT INTO t_prd_product_plate_sizes (prd_cd,siz_cd,item_siz_cd,output_paper_typ_cd,output_file_typ,dflt_plt_yn,del_yn,reg_dt) VALUES ('PRD_000066','SIZ_000147','',NULL,NULL,'Y','N',now());
INSERT INTO t_prd_product_plate_sizes (prd_cd,siz_cd,item_siz_cd,output_paper_typ_cd,output_file_typ,dflt_plt_yn,del_yn,reg_dt) VALUES ('PRD_000066','SIZ_000148','',NULL,NULL,'Y','N',now());
INSERT INTO t_prd_product_plate_sizes (prd_cd,siz_cd,item_siz_cd,output_paper_typ_cd,output_file_typ,dflt_plt_yn,del_yn,reg_dt) VALUES ('PRD_000066','SIZ_000203','',NULL,'AI','Y','N',now());
INSERT INTO t_prd_product_plate_sizes (prd_cd,siz_cd,item_siz_cd,output_paper_typ_cd,output_file_typ,dflt_plt_yn,del_yn,reg_dt) VALUES ('PRD_000066','SIZ_000204','',NULL,'*파일재작업 후 주문','Y','N',now());
INSERT INTO t_prd_product_plate_sizes (prd_cd,siz_cd,item_siz_cd,output_paper_typ_cd,output_file_typ,dflt_plt_yn,del_yn,reg_dt) VALUES ('PRD_000066','SIZ_000205','',NULL,NULL,'Y','N',now());
INSERT INTO t_prd_product_plate_sizes (prd_cd,siz_cd,item_siz_cd,output_paper_typ_cd,output_file_typ,dflt_plt_yn,del_yn,reg_dt) VALUES ('PRD_000066','SIZ_000206','',NULL,NULL,'Y','N',now());
INSERT INTO t_prd_product_plate_sizes (prd_cd,siz_cd,item_siz_cd,output_paper_typ_cd,output_file_typ,dflt_plt_yn,del_yn,reg_dt) VALUES ('PRD_000066','SIZ_000207','',NULL,NULL,'Y','N',now());
INSERT INTO t_prd_product_plate_sizes (prd_cd,siz_cd,item_siz_cd,output_paper_typ_cd,output_file_typ,dflt_plt_yn,del_yn,reg_dt) VALUES ('PRD_000066','SIZ_000208','',NULL,NULL,'Y','N',now());
INSERT INTO t_prd_product_plate_sizes (prd_cd,siz_cd,item_siz_cd,output_paper_typ_cd,output_file_typ,dflt_plt_yn,del_yn,reg_dt) VALUES ('PRD_000066','SIZ_000209','',NULL,NULL,'Y','N',now());
INSERT INTO t_prd_product_plate_sizes (prd_cd,siz_cd,item_siz_cd,output_paper_typ_cd,output_file_typ,dflt_plt_yn,del_yn,reg_dt) VALUES ('PRD_000066','SIZ_000210','',NULL,NULL,'Y','N',now());
INSERT INTO t_prd_product_plate_sizes (prd_cd,siz_cd,item_siz_cd,output_paper_typ_cd,output_file_typ,dflt_plt_yn,del_yn,reg_dt) VALUES ('PRD_000066','SIZ_000211','',NULL,NULL,'Y','N',now());
INSERT INTO t_prd_product_plate_sizes (prd_cd,siz_cd,item_siz_cd,output_paper_typ_cd,output_file_typ,dflt_plt_yn,del_yn,reg_dt) VALUES ('PRD_000066','SIZ_000225','',NULL,NULL,'Y','N',now());
INSERT INTO t_prd_product_plate_sizes (prd_cd,siz_cd,item_siz_cd,output_paper_typ_cd,output_file_typ,dflt_plt_yn,del_yn,reg_dt) VALUES ('PRD_000066','SIZ_000227','',NULL,NULL,'Y','N',now());
INSERT INTO t_prd_product_plate_sizes (prd_cd,siz_cd,item_siz_cd,output_paper_typ_cd,output_file_typ,dflt_plt_yn,del_yn,reg_dt) VALUES ('PRD_000066','SIZ_000229','',NULL,NULL,'Y','N',now());
INSERT INTO t_prd_product_plate_sizes (prd_cd,siz_cd,item_siz_cd,output_paper_typ_cd,output_file_typ,dflt_plt_yn,del_yn,reg_dt) VALUES ('PRD_000066','SIZ_000231','',NULL,NULL,'Y','N',now());
INSERT INTO t_prd_product_plate_sizes (prd_cd,siz_cd,item_siz_cd,output_paper_typ_cd,output_file_typ,dflt_plt_yn,del_yn,reg_dt) VALUES ('PRD_000066','SIZ_000233','',NULL,NULL,'Y','N',now());
INSERT INTO t_prd_product_plate_sizes (prd_cd,siz_cd,item_siz_cd,output_paper_typ_cd,output_file_typ,dflt_plt_yn,del_yn,reg_dt) VALUES ('PRD_000066','SIZ_000235','',NULL,NULL,'Y','N',now());
INSERT INTO t_prd_product_plate_sizes (prd_cd,siz_cd,item_siz_cd,output_paper_typ_cd,output_file_typ,dflt_plt_yn,del_yn,reg_dt) VALUES ('PRD_000066','SIZ_000237','',NULL,NULL,'Y','N',now());
INSERT INTO t_prd_product_plate_sizes (prd_cd,siz_cd,item_siz_cd,output_paper_typ_cd,output_file_typ,dflt_plt_yn,del_yn,reg_dt) VALUES ('PRD_000066','SIZ_000239','',NULL,NULL,'Y','N',now());
INSERT INTO t_prd_product_plate_sizes (prd_cd,siz_cd,item_siz_cd,output_paper_typ_cd,output_file_typ,dflt_plt_yn,del_yn,reg_dt) VALUES ('PRD_000066','SIZ_000241','',NULL,NULL,'Y','N',now());
INSERT INTO t_prd_product_plate_sizes (prd_cd,siz_cd,item_siz_cd,output_paper_typ_cd,output_file_typ,dflt_plt_yn,del_yn,reg_dt) VALUES ('PRD_000066','SIZ_000243','',NULL,NULL,'Y','N',now());
INSERT INTO t_prd_product_plate_sizes (prd_cd,siz_cd,item_siz_cd,output_paper_typ_cd,output_file_typ,dflt_plt_yn,del_yn,reg_dt) VALUES ('PRD_000066','SIZ_000246','',NULL,NULL,'Y','N',now());
INSERT INTO t_prd_product_plate_sizes (prd_cd,siz_cd,item_siz_cd,output_paper_typ_cd,output_file_typ,dflt_plt_yn,del_yn,reg_dt) VALUES ('PRD_000066','SIZ_000248','',NULL,NULL,'Y','N',now());
INSERT INTO t_prd_product_plate_sizes (prd_cd,siz_cd,item_siz_cd,output_paper_typ_cd,output_file_typ,dflt_plt_yn,del_yn,reg_dt) VALUES ('PRD_000067','SIZ_000050','','OUTPUT_PAPER_TYPE.03',NULL,'Y','N',now());
INSERT INTO t_prd_product_plate_sizes (prd_cd,siz_cd,item_siz_cd,output_paper_typ_cd,output_file_typ,dflt_plt_yn,del_yn,reg_dt) VALUES ('PRD_000172','SIZ_000251','',NULL,NULL,'Y','N',now());
INSERT INTO t_prd_product_plate_sizes (prd_cd,siz_cd,item_siz_cd,output_paper_typ_cd,output_file_typ,dflt_plt_yn,del_yn,reg_dt) VALUES ('PRD_000173','SIZ_000181','',NULL,NULL,'Y','N',now());
INSERT INTO t_prd_product_plate_sizes (prd_cd,siz_cd,item_siz_cd,output_paper_typ_cd,output_file_typ,dflt_plt_yn,del_yn,reg_dt) VALUES ('PRD_000176','SIZ_000180','',NULL,'PDF','Y','N',now());
INSERT INTO t_prd_product_plate_sizes (prd_cd,siz_cd,item_siz_cd,output_paper_typ_cd,output_file_typ,dflt_plt_yn,del_yn,reg_dt) VALUES ('PRD_000176','SIZ_000376','',NULL,'PDF','Y','N',now());
INSERT INTO t_prd_product_plate_sizes (prd_cd,siz_cd,item_siz_cd,output_paper_typ_cd,output_file_typ,dflt_plt_yn,del_yn,reg_dt) VALUES ('PRD_000177','SIZ_000171','',NULL,NULL,'Y','N',now());
INSERT INTO t_prd_product_plate_sizes (prd_cd,siz_cd,item_siz_cd,output_paper_typ_cd,output_file_typ,dflt_plt_yn,del_yn,reg_dt) VALUES ('PRD_000178','SIZ_000378','',NULL,NULL,'Y','N',now());
INSERT INTO t_prd_product_plate_sizes (prd_cd,siz_cd,item_siz_cd,output_paper_typ_cd,output_file_typ,dflt_plt_yn,del_yn,reg_dt) VALUES ('PRD_000179','SIZ_000007','',NULL,NULL,'Y','N',now());
INSERT INTO t_prd_product_plate_sizes (prd_cd,siz_cd,item_siz_cd,output_paper_typ_cd,output_file_typ,dflt_plt_yn,del_yn,reg_dt) VALUES ('PRD_000179','SIZ_000381','',NULL,NULL,'Y','N',now());
INSERT INTO t_prd_product_plate_sizes (prd_cd,siz_cd,item_siz_cd,output_paper_typ_cd,output_file_typ,dflt_plt_yn,del_yn,reg_dt) VALUES ('PRD_000181','SIZ_000382','',NULL,NULL,'Y','N',now());
COMMIT;