-- ===== AUTO-GENERATED by gen_naming_sql.py — DO NOT HAND-EDIT =====
-- comp_nm/note 멱등 가드 UPDATE (cleanup v2 verbatim)
-- comp 대상행=111 · comp_typ_cd 보강=1 · 합계 행=112
-- (comp_nm UPDATE=110 · note UPDATE=2 · both=1)

-- [BLOCK:NAME_NOTE]
UPDATE t_prc_price_components SET note = '아크릴코롯토 인쇄·가공 포함가. 사이즈·수량별 단가표.' WHERE comp_cd = 'COMP_ACRYL_COROTTO' AND (note IS DISTINCT FROM '아크릴코롯토 인쇄·가공 포함가. 사이즈·수량별 단가표.');  -- C
UPDATE t_prc_price_components SET comp_nm = '제본비 탁상캘린더(130)' WHERE comp_cd = 'COMP_BIND_CAL_DESK130' AND (comp_nm IS DISTINCT FROM '제본비 탁상캘린더(130)');  -- A-4
UPDATE t_prc_price_components SET comp_nm = '제본비 탁상캘린더(220)' WHERE comp_cd = 'COMP_BIND_CAL_DESK220' AND (comp_nm IS DISTINCT FROM '제본비 탁상캘린더(220)');  -- A-4
UPDATE t_prc_price_components SET comp_nm = '제본비 탁상캘린더(미니)' WHERE comp_cd = 'COMP_BIND_CAL_DESKMINI' AND (comp_nm IS DISTINCT FROM '제본비 탁상캘린더(미니)');  -- A-4
UPDATE t_prc_price_components SET comp_nm = '제본비 벽걸이캘린더' WHERE comp_cd = 'COMP_BIND_CAL_WALL' AND (comp_nm IS DISTINCT FROM '제본비 벽걸이캘린더');  -- A-4
UPDATE t_prc_price_components SET comp_nm = '제본비 하드커버무선' WHERE comp_cd = 'COMP_BIND_HC_MUSEON' AND (comp_nm IS DISTINCT FROM '제본비 하드커버무선');  -- A-4
UPDATE t_prc_price_components SET comp_nm = '제본비 하드커버트윈링' WHERE comp_cd = 'COMP_BIND_HC_TWINRING' AND (comp_nm IS DISTINCT FROM '제본비 하드커버트윈링');  -- A-4
UPDATE t_prc_price_components SET comp_nm = '제본비 중철' WHERE comp_cd = 'COMP_BIND_JUNGCHEOL' AND (comp_nm IS DISTINCT FROM '제본비 중철');  -- A-4
UPDATE t_prc_price_components SET comp_nm = '제본비 무선' WHERE comp_cd = 'COMP_BIND_MUSEON' AND (comp_nm IS DISTINCT FROM '제본비 무선');  -- A-4
UPDATE t_prc_price_components SET comp_nm = '제본비 PUR' WHERE comp_cd = 'COMP_BIND_PUR' AND (comp_nm IS DISTINCT FROM '제본비 PUR');  -- A-4
UPDATE t_prc_price_components SET comp_nm = '제본비 싸바리바인더' WHERE comp_cd = 'COMP_BIND_SSABARI' AND (comp_nm IS DISTINCT FROM '제본비 싸바리바인더');  -- A-4
UPDATE t_prc_price_components SET comp_nm = '제본비 트윈링' WHERE comp_cd = 'COMP_BIND_TWINRING' AND (comp_nm IS DISTINCT FROM '제본비 트윈링');  -- A-4
UPDATE t_prc_price_components SET comp_nm = '커팅 완제품가 완칼(모양엽서·라벨택)' WHERE comp_cd = 'COMP_CUT_FULL_DIECUT' AND (comp_nm IS DISTINCT FROM '커팅 완제품가 완칼(모양엽서·라벨택)');  -- A-7
UPDATE t_prc_price_components SET comp_nm = '커팅 완제품가 완칼+타공1구' WHERE comp_cd = 'COMP_CUT_FULL_PERF_1H6' AND (comp_nm IS DISTINCT FROM '커팅 완제품가 완칼+타공1구');  -- A-7
UPDATE t_prc_price_components SET comp_nm = '커팅 완제품가 완칼+타공2구' WHERE comp_cd = 'COMP_CUT_FULL_PERF_2H6' AND (comp_nm IS DISTINCT FROM '커팅 완제품가 완칼+타공2구');  -- A-7
UPDATE t_prc_price_components SET comp_nm = '타공비 1구(6mm)' WHERE comp_cd = 'COMP_CUT_PERF_1H6' AND (comp_nm IS DISTINCT FROM '타공비 1구(6mm)');  -- A-6
UPDATE t_prc_price_components SET comp_nm = '접지비 카드 2단' WHERE comp_cd = 'COMP_FOLD_CARD_2H' AND (comp_nm IS DISTINCT FROM '접지비 카드 2단');  -- A-5
UPDATE t_prc_price_components SET comp_nm = '접지비 카드 3단' WHERE comp_cd = 'COMP_FOLD_CARD_3H' AND (comp_nm IS DISTINCT FROM '접지비 카드 3단');  -- A-5
UPDATE t_prc_price_components SET comp_nm = '접지비 카드 6크리즈' WHERE comp_cd = 'COMP_FOLD_CARD_6CR' AND (comp_nm IS DISTINCT FROM '접지비 카드 6크리즈');  -- A-5
UPDATE t_prc_price_components SET comp_nm = '접지비 리플렛 3단' WHERE comp_cd = 'COMP_FOLD_LEAF_3FOLD' AND (comp_nm IS DISTINCT FROM '접지비 리플렛 3단');  -- A-5
UPDATE t_prc_price_components SET comp_nm = '접지비 리플렛 4단아코디언' WHERE comp_cd = 'COMP_FOLD_LEAF_4ACC' AND (comp_nm IS DISTINCT FROM '접지비 리플렛 4단아코디언');  -- A-5
UPDATE t_prc_price_components SET comp_nm = '접지비 리플렛 4단게이트' WHERE comp_cd = 'COMP_FOLD_LEAF_4GATE' AND (comp_nm IS DISTINCT FROM '접지비 리플렛 4단게이트');  -- A-5
UPDATE t_prc_price_components SET comp_nm = '접지비 리플렛 반접지' WHERE comp_cd = 'COMP_FOLD_LEAF_HALF' AND (comp_nm IS DISTINCT FROM '접지비 리플렛 반접지');  -- A-5
UPDATE t_prc_price_components SET comp_nm = '합판도무송 완제품가(형상·소재별)' WHERE comp_cd = 'COMP_GANGPAN_PRINT' AND (comp_nm IS DISTINCT FROM '합판도무송 완제품가(형상·소재별)');  -- A-10
UPDATE t_prc_price_components SET comp_nm = '투명명함 완제품가 단면(용지포함)' WHERE comp_cd = 'COMP_NAMECARD_CLEAR_S1' AND (comp_nm IS DISTINCT FROM '투명명함 완제품가 단면(용지포함)');  -- A-1
UPDATE t_prc_price_components SET comp_nm = '코팅명함 완제품가 단면(용지포함)' WHERE comp_cd = 'COMP_NAMECARD_COAT_S1' AND (comp_nm IS DISTINCT FROM '코팅명함 완제품가 단면(용지포함)');  -- A-1
UPDATE t_prc_price_components SET comp_nm = '코팅명함 완제품가 양면(용지포함)' WHERE comp_cd = 'COMP_NAMECARD_COAT_S2' AND (comp_nm IS DISTINCT FROM '코팅명함 완제품가 양면(용지포함)');  -- A-1
UPDATE t_prc_price_components SET comp_nm = '오리지널박명함 완제품가 단면·홀로그램/트윙클(종이+동판+박)' WHERE comp_cd = 'COMP_NAMECARD_FOIL_S1_HOLO' AND (comp_nm IS DISTINCT FROM '오리지널박명함 완제품가 단면·홀로그램/트윙클(종이+동판+박)');  -- A-2
UPDATE t_prc_price_components SET comp_nm = '오리지널박명함 완제품가 단면·일반박(종이+동판+박)' WHERE comp_cd = 'COMP_NAMECARD_FOIL_S1_STD' AND (comp_nm IS DISTINCT FROM '오리지널박명함 완제품가 단면·일반박(종이+동판+박)');  -- A-2
UPDATE t_prc_price_components SET comp_nm = '오리지널박명함 완제품가 양면·홀로그램/트윙클(종이+동판+박)' WHERE comp_cd = 'COMP_NAMECARD_FOIL_S2_HOLO' AND (comp_nm IS DISTINCT FROM '오리지널박명함 완제품가 양면·홀로그램/트윙클(종이+동판+박)');  -- A-2
UPDATE t_prc_price_components SET comp_nm = '오리지널박명함 완제품가 양면·일반박(종이+동판+박)' WHERE comp_cd = 'COMP_NAMECARD_FOIL_S2_STD' AND (comp_nm IS DISTINCT FROM '오리지널박명함 완제품가 양면·일반박(종이+동판+박)');  -- A-2
UPDATE t_prc_price_components SET comp_nm = '박·형압 동판셋업비 단면' WHERE comp_cd = 'COMP_NAMECARD_FOIL_SETUP_S1_STD' AND (comp_nm IS DISTINCT FROM '박·형압 동판셋업비 단면');  -- A-3
UPDATE t_prc_price_components SET comp_nm = '박·형압 동판셋업비 양면' WHERE comp_cd = 'COMP_NAMECARD_FOIL_SETUP_S2_STD' AND (comp_nm IS DISTINCT FROM '박·형압 동판셋업비 양면');  -- A-3
UPDATE t_prc_price_components SET comp_nm = '미니모양명함 완제품가 단면(용지포함)' WHERE comp_cd = 'COMP_NAMECARD_MINISHAPE_S1' AND (comp_nm IS DISTINCT FROM '미니모양명함 완제품가 단면(용지포함)');  -- A-1
UPDATE t_prc_price_components SET comp_nm = '미니모양명함 완제품가 양면(용지포함)' WHERE comp_cd = 'COMP_NAMECARD_MINISHAPE_S2' AND (comp_nm IS DISTINCT FROM '미니모양명함 완제품가 양면(용지포함)');  -- A-1
UPDATE t_prc_price_components SET comp_nm = '펄명함(스타드림) 완제품가 단면(용지포함)' WHERE comp_cd = 'COMP_NAMECARD_PEARL_S1' AND (comp_nm IS DISTINCT FROM '펄명함(스타드림) 완제품가 단면(용지포함)');  -- A-1
UPDATE t_prc_price_components SET comp_nm = '펄명함(스타드림) 완제품가 양면(용지포함)' WHERE comp_cd = 'COMP_NAMECARD_PEARL_S2' AND (comp_nm IS DISTINCT FROM '펄명함(스타드림) 완제품가 양면(용지포함)');  -- A-1
UPDATE t_prc_price_components SET comp_nm = '프리미엄명함A 완제품가 단면(용지포함)' WHERE comp_cd = 'COMP_NAMECARD_PREMIUM_S1_MGA' AND (comp_nm IS DISTINCT FROM '프리미엄명함A 완제품가 단면(용지포함)');  -- A-1
UPDATE t_prc_price_components SET comp_nm = '프리미엄명함B 완제품가 단면(용지포함)' WHERE comp_cd = 'COMP_NAMECARD_PREMIUM_S1_MGB' AND (comp_nm IS DISTINCT FROM '프리미엄명함B 완제품가 단면(용지포함)');  -- A-1
UPDATE t_prc_price_components SET comp_nm = '프리미엄명함A 완제품가 양면(용지포함)' WHERE comp_cd = 'COMP_NAMECARD_PREMIUM_S2_MGA' AND (comp_nm IS DISTINCT FROM '프리미엄명함A 완제품가 양면(용지포함)');  -- A-1
UPDATE t_prc_price_components SET comp_nm = '프리미엄명함B 완제품가 양면(용지포함)' WHERE comp_cd = 'COMP_NAMECARD_PREMIUM_S2_MGB' AND (comp_nm IS DISTINCT FROM '프리미엄명함B 완제품가 양면(용지포함)');  -- A-1
UPDATE t_prc_price_components SET comp_nm = '모양명함 완제품가 단면(용지포함)' WHERE comp_cd = 'COMP_NAMECARD_SHAPE_S1' AND (comp_nm IS DISTINCT FROM '모양명함 완제품가 단면(용지포함)');  -- A-1
UPDATE t_prc_price_components SET comp_nm = '모양명함 완제품가 양면(용지포함)' WHERE comp_cd = 'COMP_NAMECARD_SHAPE_S2' AND (comp_nm IS DISTINCT FROM '모양명함 완제품가 양면(용지포함)');  -- A-1
UPDATE t_prc_price_components SET comp_nm = '스탠다드명함 완제품가 단면(용지포함)' WHERE comp_cd = 'COMP_NAMECARD_STD_S1' AND (comp_nm IS DISTINCT FROM '스탠다드명함 완제품가 단면(용지포함)');  -- A-1
UPDATE t_prc_price_components SET comp_nm = '스탠다드명함 완제품가 양면(용지포함)' WHERE comp_cd = 'COMP_NAMECARD_STD_S2' AND (comp_nm IS DISTINCT FROM '스탠다드명함 완제품가 양면(용지포함)');  -- A-1
UPDATE t_prc_price_components SET comp_nm = '화이트인쇄명함 완제품가 단면·코팅(용지포함)' WHERE comp_cd = 'COMP_NAMECARD_WHITE_S1W_CL' AND (comp_nm IS DISTINCT FROM '화이트인쇄명함 완제품가 단면·코팅(용지포함)');  -- A-1
UPDATE t_prc_price_components SET comp_nm = '화이트인쇄명함 완제품가 단면·무코팅(용지포함)' WHERE comp_cd = 'COMP_NAMECARD_WHITE_S1W_NOCL' AND (comp_nm IS DISTINCT FROM '화이트인쇄명함 완제품가 단면·무코팅(용지포함)');  -- A-1
UPDATE t_prc_price_components SET comp_nm = '화이트인쇄명함 완제품가 양면·코팅(용지포함)' WHERE comp_cd = 'COMP_NAMECARD_WHITE_S2W_CL' AND (comp_nm IS DISTINCT FROM '화이트인쇄명함 완제품가 양면·코팅(용지포함)');  -- A-1
UPDATE t_prc_price_components SET comp_nm = '화이트인쇄명함 완제품가 양면·무코팅(용지포함)' WHERE comp_cd = 'COMP_NAMECARD_WHITE_S2W_NOCL' AND (comp_nm IS DISTINCT FROM '화이트인쇄명함 완제품가 양면·무코팅(용지포함)');  -- A-1
UPDATE t_prc_price_components SET comp_nm = '엽서북 완제품가 단면·20p' WHERE comp_cd = 'COMP_PCB_S1_20P' AND (comp_nm IS DISTINCT FROM '엽서북 완제품가 단면·20p');  -- A-8
UPDATE t_prc_price_components SET comp_nm = '엽서북 완제품가 단면·30p' WHERE comp_cd = 'COMP_PCB_S1_30P' AND (comp_nm IS DISTINCT FROM '엽서북 완제품가 단면·30p');  -- A-8
UPDATE t_prc_price_components SET comp_nm = '엽서북 완제품가 양면·20p' WHERE comp_cd = 'COMP_PCB_S2_20P' AND (comp_nm IS DISTINCT FROM '엽서북 완제품가 양면·20p');  -- A-8
UPDATE t_prc_price_components SET comp_nm = '엽서북 완제품가 양면·30p' WHERE comp_cd = 'COMP_PCB_S2_30P' AND (comp_nm IS DISTINCT FROM '엽서북 완제품가 양면·30p');  -- A-8
UPDATE t_prc_price_components SET comp_nm = '포토카드 완제품가 대량' WHERE comp_cd = 'COMP_PHOTOCARD_BULK' AND (comp_nm IS DISTINCT FROM '포토카드 완제품가 대량');  -- A-9
UPDATE t_prc_price_components SET comp_nm = '포토카드 완제품가 투명세트' WHERE comp_cd = 'COMP_PHOTOCARD_CLEAR_SET' AND (comp_nm IS DISTINCT FROM '포토카드 완제품가 투명세트');  -- A-9
UPDATE t_prc_price_components SET comp_nm = '포토카드 완제품가 일반세트' WHERE comp_cd = 'COMP_PHOTOCARD_SET' AND (comp_nm IS DISTINCT FROM '포토카드 완제품가 일반세트');  -- A-9
UPDATE t_prc_price_components SET comp_nm = '현수막 각목(900mm 초과)+끈(4개) 추가가격' WHERE comp_cd = 'COMP_POPT_BNR_GAKMOK_STR_900_4_GT' AND (comp_nm IS DISTINCT FROM '현수막 각목(900mm 초과)+끈(4개) 추가가격');  -- A-12
UPDATE t_prc_price_components SET comp_nm = '현수막 각목(900mm이하)+끈(4개) 추가가격' WHERE comp_cd = 'COMP_POPT_BNR_GAKMOK_STR_900_4_LE' AND (comp_nm IS DISTINCT FROM '현수막 각목(900mm이하)+끈(4개) 추가가격');  -- A-12
UPDATE t_prc_price_components SET comp_nm = '메쉬현수막 큐방(4개) 추가가격' WHERE comp_cd = 'COMP_POSTEROPT_BANNER_MESH_ADD_QBANG_4' AND (comp_nm IS DISTINCT FROM '메쉬현수막 큐방(4개) 추가가격');  -- A-12
UPDATE t_prc_price_components SET comp_nm = '메쉬현수막 끈(4개) 추가가격' WHERE comp_cd = 'COMP_POSTEROPT_BANNER_MESH_ADD_STRING_4' AND (comp_nm IS DISTINCT FROM '메쉬현수막 끈(4개) 추가가격');  -- A-12
UPDATE t_prc_price_components SET comp_nm = '메쉬현수막 타공(4개) 추가가격' WHERE comp_cd = 'COMP_POSTEROPT_BANNER_MESH_PROC_PUNCH_4' AND (comp_nm IS DISTINCT FROM '메쉬현수막 타공(4개) 추가가격');  -- A-12
UPDATE t_prc_price_components SET comp_nm = '메쉬현수막 타공(6개) 추가가격' WHERE comp_cd = 'COMP_POSTEROPT_BANNER_MESH_PROC_PUNCH_6' AND (comp_nm IS DISTINCT FROM '메쉬현수막 타공(6개) 추가가격');  -- A-12
UPDATE t_prc_price_components SET comp_nm = '메쉬현수막 타공(8개) 추가가격' WHERE comp_cd = 'COMP_POSTEROPT_BANNER_MESH_PROC_PUNCH_8' AND (comp_nm IS DISTINCT FROM '메쉬현수막 타공(8개) 추가가격');  -- A-12
UPDATE t_prc_price_components SET comp_nm = '일반현수막 큐방(4개) 추가가격' WHERE comp_cd = 'COMP_POSTEROPT_BANNER_NORMAL_ADD_QBANG_4' AND (comp_nm IS DISTINCT FROM '일반현수막 큐방(4개) 추가가격');  -- A-12
UPDATE t_prc_price_components SET comp_nm = '일반현수막 끈(4개) 추가가격' WHERE comp_cd = 'COMP_POSTEROPT_BANNER_NORMAL_ADD_STRING_4' AND (comp_nm IS DISTINCT FROM '일반현수막 끈(4개) 추가가격');  -- A-12
UPDATE t_prc_price_components SET comp_nm = '일반현수막 봉미싱 추가가격' WHERE comp_cd = 'COMP_POSTEROPT_BANNER_NORMAL_PROC_BONGSEW' AND (comp_nm IS DISTINCT FROM '일반현수막 봉미싱 추가가격');  -- A-12
UPDATE t_prc_price_components SET comp_nm = '일반현수막 열재단 추가가격' WHERE comp_cd = 'COMP_POSTEROPT_BANNER_NORMAL_PROC_CUTEDGE' AND (comp_nm IS DISTINCT FROM '일반현수막 열재단 추가가격');  -- A-12
UPDATE t_prc_price_components SET comp_nm = '일반현수막 양면테잎 추가가격' WHERE comp_cd = 'COMP_POSTEROPT_BANNER_NORMAL_PROC_DTAPE' AND (comp_nm IS DISTINCT FROM '일반현수막 양면테잎 추가가격');  -- A-12
UPDATE t_prc_price_components SET comp_nm = '일반현수막 타공(4개) 추가가격' WHERE comp_cd = 'COMP_POSTEROPT_BANNER_NORMAL_PROC_PUNCH_4' AND (comp_nm IS DISTINCT FROM '일반현수막 타공(4개) 추가가격');  -- A-12
UPDATE t_prc_price_components SET comp_nm = '일반현수막 타공(6개) 추가가격' WHERE comp_cd = 'COMP_POSTEROPT_BANNER_NORMAL_PROC_PUNCH_6' AND (comp_nm IS DISTINCT FROM '일반현수막 타공(6개) 추가가격');  -- A-12
UPDATE t_prc_price_components SET comp_nm = '일반현수막 타공(8개) 추가가격' WHERE comp_cd = 'COMP_POSTEROPT_BANNER_NORMAL_PROC_PUNCH_8' AND (comp_nm IS DISTINCT FROM '일반현수막 타공(8개) 추가가격');  -- A-12
UPDATE t_prc_price_components SET comp_nm = '캔버스행잉포스터 우드행거+면끈 추가가격' WHERE comp_cd = 'COMP_POSTEROPT_CANVAS_HANGING_WOODHANGER' AND (comp_nm IS DISTINCT FROM '캔버스행잉포스터 우드행거+면끈 추가가격');  -- A-12
UPDATE t_prc_price_components SET comp_nm = '족자포스터 천정형고리 추가가격' WHERE comp_cd = 'COMP_POSTEROPT_JOKJA_CEILHOOK' AND (comp_nm IS DISTINCT FROM '족자포스터 천정형고리 추가가격');  -- A-12
UPDATE t_prc_price_components SET comp_nm = '린넨우드봉족자 우드봉+면끈 추가가격' WHERE comp_cd = 'COMP_POSTEROPT_LINEN_WOODBONG_WOODBONG' AND (comp_nm IS DISTINCT FROM '린넨우드봉족자 우드봉+면끈 추가가격');  -- A-12
UPDATE t_prc_price_components SET comp_nm = 'PET배너 실내용배너거치대 추가가격' WHERE comp_cd = 'COMP_POSTEROPT_PET_BANNER_STAND_IN' AND (comp_nm IS DISTINCT FROM 'PET배너 실내용배너거치대 추가가격');  -- A-12
UPDATE t_prc_price_components SET comp_nm = 'PET배너 실외용배너거치대(단면용) 추가가격' WHERE comp_cd = 'COMP_POSTEROPT_PET_BANNER_STAND_OUT_S1' AND (comp_nm IS DISTINCT FROM 'PET배너 실외용배너거치대(단면용) 추가가격');  -- A-12
UPDATE t_prc_price_components SET comp_nm = 'PET배너 실외용배너거치대(양면용) 추가가격' WHERE comp_cd = 'COMP_POSTEROPT_PET_BANNER_STAND_OUT_S2' AND (comp_nm IS DISTINCT FROM 'PET배너 실외용배너거치대(양면용) 추가가격');  -- A-12
UPDATE t_prc_price_components SET comp_nm = '유광아크릴스티커 완제품가' WHERE comp_cd = 'COMP_POSTER_ACRYLSTK_GLOSS' AND (comp_nm IS DISTINCT FROM '유광아크릴스티커 완제품가');  -- A-11
UPDATE t_prc_price_components SET comp_nm = '미러아크릴스티커 완제품가' WHERE comp_cd = 'COMP_POSTER_ACRYLSTK_MIRROR' AND (comp_nm IS DISTINCT FROM '미러아크릴스티커 완제품가');  -- A-11
UPDATE t_prc_price_components SET comp_nm = '접착방수포스터 완제품가[레거시]' WHERE comp_cd = 'COMP_POSTER_ADH_WATERPROOF_PVC' AND (comp_nm IS DISTINCT FROM '접착방수포스터 완제품가[레거시]');  -- A-11-legacy
UPDATE t_prc_price_components SET comp_nm = '아트패브릭포스터 완제품가[레거시]' WHERE comp_cd = 'COMP_POSTER_ARTFABRIC_GRAPHIC' AND (comp_nm IS DISTINCT FROM '아트패브릭포스터 완제품가[레거시]');  -- A-11-legacy
UPDATE t_prc_price_components SET comp_nm = '캔버스 행잉포스터 완제품가' WHERE comp_cd = 'COMP_POSTER_CANVAS_HANGING' AND (comp_nm IS DISTINCT FROM '캔버스 행잉포스터 완제품가');  -- A-11
UPDATE t_prc_price_components SET comp_nm = '폼보드(블랙) 완제품가' WHERE comp_cd = 'COMP_POSTER_FOAMBOARD_BLACK' AND (comp_nm IS DISTINCT FROM '폼보드(블랙) 완제품가');  -- A-11
UPDATE t_prc_price_components SET comp_nm = '폼보드(화이트) 완제품가' WHERE comp_cd = 'COMP_POSTER_FOAMBOARD_WHITE' AND (comp_nm IS DISTINCT FROM '폼보드(화이트) 완제품가');  -- A-11
UPDATE t_prc_price_components SET comp_nm = '포맥스보드(화이트3mm) 완제품가' WHERE comp_cd = 'COMP_POSTER_FOMEXBOARD_WHITE3MM' AND (comp_nm IS DISTINCT FROM '포맥스보드(화이트3mm) 완제품가');  -- A-11
UPDATE t_prc_price_components SET comp_nm = '포맥스보드(화이트5mm) 완제품가' WHERE comp_cd = 'COMP_POSTER_FOMEXBOARD_WHITE5MM' AND (comp_nm IS DISTINCT FROM '포맥스보드(화이트5mm) 완제품가');  -- A-11
UPDATE t_prc_price_components SET comp_nm = '프레임리스우드액자 완제품가' WHERE comp_cd = 'COMP_POSTER_FRAMELESS_WOOD' AND (comp_nm IS DISTINCT FROM '프레임리스우드액자 완제품가');  -- A-11
UPDATE t_prc_price_components SET comp_nm = '족자포스터 완제품가' WHERE comp_cd = 'COMP_POSTER_JOKJA' AND (comp_nm IS DISTINCT FROM '족자포스터 완제품가');  -- A-11
UPDATE t_prc_price_components SET comp_nm = '레더아트프린트 완제품가[레거시]' WHERE comp_cd = 'COMP_POSTER_LEATHER_ARTPRINT' AND (comp_nm IS DISTINCT FROM '레더아트프린트 완제품가[레거시]');  -- A-11-legacy
UPDATE t_prc_price_components SET comp_nm = '레더아트액자 완제품가' WHERE comp_cd = 'COMP_POSTER_LEATHER_FRAME' AND (comp_nm IS DISTINCT FROM '레더아트액자 완제품가');  -- A-11
UPDATE t_prc_price_components SET comp_nm = '린넨 우드봉 족자 완제품가' WHERE comp_cd = 'COMP_POSTER_LINEN_WOODBONG' AND (comp_nm IS DISTINCT FROM '린넨 우드봉 족자 완제품가');  -- A-11
UPDATE t_prc_price_components SET comp_nm = '메쉬배너 완제품가' WHERE comp_cd = 'COMP_POSTER_MESH_BANNER' AND (comp_nm IS DISTINCT FROM '메쉬배너 완제품가');  -- A-11
UPDATE t_prc_price_components SET comp_nm = '메쉬프린트 완제품가[레거시]' WHERE comp_cd = 'COMP_POSTER_MESH_PRINT' AND (comp_nm IS DISTINCT FROM '메쉬프린트 완제품가[레거시]');  -- A-11-legacy
UPDATE t_prc_price_components SET comp_nm = '미니배너 완제품가' WHERE comp_cd = 'COMP_POSTER_MINI_BANNER' AND (comp_nm IS DISTINCT FROM '미니배너 완제품가');  -- A-11
UPDATE t_prc_price_components SET comp_nm = '미니보드스탠딩 완제품가' WHERE comp_cd = 'COMP_POSTER_MINI_STANDBOARD' AND (comp_nm IS DISTINCT FROM '미니보드스탠딩 완제품가');  -- A-11
UPDATE t_prc_price_components SET comp_nm = 'PET배너 완제품가' WHERE comp_cd = 'COMP_POSTER_PET_BANNER' AND (comp_nm IS DISTINCT FROM 'PET배너 완제품가');  -- A-11
UPDATE t_prc_price_components SET comp_nm = '홀로그램 시트커팅 완제품가' WHERE comp_cd = 'COMP_POSTER_SHEETCUT_HOLO' AND (comp_nm IS DISTINCT FROM '홀로그램 시트커팅 완제품가');  -- A-11
UPDATE t_prc_price_components SET comp_nm = '무광시트커팅 완제품가' WHERE comp_cd = 'COMP_POSTER_SHEETCUT_MATTE' AND (comp_nm IS DISTINCT FROM '무광시트커팅 완제품가');  -- A-11
UPDATE t_prc_price_components SET comp_nm = '타이벡프린트 완제품가[레거시]' WHERE comp_cd = 'COMP_POSTER_TYVEK_PRINT' AND (comp_nm IS DISTINCT FROM '타이벡프린트 완제품가[레거시]');  -- A-11-legacy
UPDATE t_prc_price_components SET comp_nm = '방수포스터 완제품가[레거시]' WHERE comp_cd = 'COMP_POSTER_WATERPROOF_PET' AND (comp_nm IS DISTINCT FROM '방수포스터 완제품가[레거시]');  -- A-11-legacy
UPDATE t_prc_price_components SET comp_nm = '귀돌이비 직각' WHERE comp_cd = 'COMP_PP_CORNER_RIGHT' AND (comp_nm IS DISTINCT FROM '귀돌이비 직각');  -- B/refinement
UPDATE t_prc_price_components SET comp_nm = '귀돌이비 둥근' WHERE comp_cd = 'COMP_PP_CORNER_ROUND' AND (comp_nm IS DISTINCT FROM '귀돌이비 둥근');  -- B/refinement
UPDATE t_prc_price_components SET comp_nm = '오시비 2줄' WHERE comp_cd = 'COMP_PP_CREASE_2L' AND (comp_nm IS DISTINCT FROM '오시비 2줄');  -- B
UPDATE t_prc_price_components SET comp_nm = '오시비 3줄' WHERE comp_cd = 'COMP_PP_CREASE_3L' AND (comp_nm IS DISTINCT FROM '오시비 3줄');  -- B
UPDATE t_prc_price_components SET comp_nm = '미싱비 2줄' WHERE comp_cd = 'COMP_PP_PERF_2L' AND (comp_nm IS DISTINCT FROM '미싱비 2줄');  -- B
UPDATE t_prc_price_components SET comp_nm = '미싱비 3줄' WHERE comp_cd = 'COMP_PP_PERF_3L' AND (comp_nm IS DISTINCT FROM '미싱비 3줄');  -- B
UPDATE t_prc_price_components SET comp_nm = '디지털인쇄비(단면)' WHERE comp_cd = 'COMP_PRINT_DIGITAL_S1' AND (comp_nm IS DISTINCT FROM '디지털인쇄비(단면)');  -- B
UPDATE t_prc_price_components SET comp_nm = '스티커 완제품가 팩(54장1세트)' WHERE comp_cd = 'COMP_STK_PACK' AND (comp_nm IS DISTINCT FROM '스티커 완제품가 팩(54장1세트)');  -- A-10
UPDATE t_prc_price_components SET comp_nm = '스티커 완제품가(소재·규격)' WHERE comp_cd = 'COMP_STK_PRINT' AND (comp_nm IS DISTINCT FROM '스티커 완제품가(소재·규격)');  -- A-10
UPDATE t_prc_price_components SET comp_nm = '타투스티커 완제품가(3장세트)', note = '타투스티커 완제품가. 3장 1세트당 합산가(합가형).' WHERE comp_cd = 'COMP_STK_TATTOO' AND (comp_nm IS DISTINCT FROM '타투스티커 완제품가(3장세트)' OR note IS DISTINCT FROM '타투스티커 완제품가. 3장 1세트당 합산가(합가형).');  -- A-10/C
UPDATE t_prc_price_components SET comp_nm = '떡메모지 완제품가(권당장수)' WHERE comp_cd = 'COMP_TTEOKME' AND (comp_nm IS DISTINCT FROM '떡메모지 완제품가(권당장수)');  -- A-10

-- [BLOCK:TYP_FIX]
UPDATE t_prc_price_components SET comp_typ_cd = 'PRC_COMPONENT_TYPE.06' WHERE comp_cd = 'COMP_STK_TATTOO' AND comp_typ_cd IS DISTINCT FROM 'PRC_COMPONENT_TYPE.06';  -- C: comp_typ_cd 보강

-- [EXCLUDED — 적재 대상 아님 (task §4)]
--   COMP_POSTEROPT_BANNER_MESH_PROC_OPT : 가격행 0행 빈 더미 — use_yn=N 검토(별도)
--   COMP_POPT_BNR_GAKMOK_STR_900_4 : 가격행 0행 base 빈 더미 — _GT/_LE만 활성(별도)

-- STATS: {'total_name_updates': 110, 'total_note_updates': 2, 'both': 1, 'name_only': 109, 'note_only': 1, 'typ_fix': 1, 'rows_touched': 112}
