-- W2_body_wiring.sql — 각 공식 disp_seq=1 = 자기 본체 comp 배선 (addtn_yn='Y' 메타·엔진무관)
-- 멱등: (frm_cd,comp_cd) NOT EXISTS. 단가행 재적재 0.
INSERT INTO t_prc_formula_components (frm_cd, comp_cd, disp_seq, addtn_yn, reg_dt)
SELECT v.frm_cd, v.comp_cd, 1, 'Y', now()
FROM (VALUES
  ('PRF_POSTER_ARTPRINT','COMP_POSTER_ARTPRINT_PHOTO'),
  ('PRF_POSTER_ARTPAPER','COMP_POSTER_ARTPAPER_MATTE'),
  ('PRF_POSTER_WATERPROOF','COMP_POSTER_WATERPROOF_PET'),
  ('PRF_POSTER_ADH_WP','COMP_POSTER_ADH_WATERPROOF_PVC'),
  ('PRF_POSTER_ADH_CLEAR','COMP_POSTER_ADH_CLEAR_PVC'),
  ('PRF_POSTER_ARTFABRIC','COMP_POSTER_ARTFABRIC_GRAPHIC'),
  ('PRF_POSTER_LINEN','COMP_POSTER_LINEN_FABRIC'),
  ('PRF_POSTER_CANVAS','COMP_POSTER_CANVAS_FABRIC'),
  ('PRF_POSTER_LEATHER_AP','COMP_POSTER_LEATHER_ARTPRINT'),
  ('PRF_POSTER_TYVEK','COMP_POSTER_TYVEK_PRINT'),
  ('PRF_POSTER_MESH','COMP_POSTER_MESH_PRINT'),
  ('PRF_POSTER_FOAMBOARD','COMP_POSTER_FOAMBOARD_WHITE'),
  ('PRF_POSTER_FOMEXBOARD','COMP_POSTER_FOMEXBOARD_WHITE3MM'),
  ('PRF_POSTER_FRAMELESS','COMP_POSTER_FRAMELESS_WOOD'),
  ('PRF_POSTER_LEATHER_FRAME','COMP_POSTER_LEATHER_FRAME'),
  ('PRF_POSTER_CANVAS_HANGING','COMP_POSTER_CANVAS_HANGING'),
  ('PRF_POSTER_LINEN_WOODBONG','COMP_POSTER_LINEN_WOODBONG'),
  ('PRF_POSTER_JOKJA','COMP_POSTER_JOKJA'),
  ('PRF_POSTER_PET_BANNER','COMP_POSTER_PET_BANNER'),
  ('PRF_POSTER_MESH_BANNER','COMP_POSTER_MESH_BANNER'),
  ('PRF_POSTER_BANNER_N','COMP_POSTER_BANNER_NORMAL'),
  ('PRF_POSTER_BANNER_M','COMP_POSTER_BANNER_MESH'),
  ('PRF_POSTER_SHEETCUT_MATTE','COMP_POSTER_SHEETCUT_MATTE'),
  ('PRF_POSTER_SHEETCUT_HOLO','COMP_POSTER_SHEETCUT_HOLO'),
  ('PRF_POSTER_ACRYLSTK_GLOSS','COMP_POSTER_ACRYLSTK_GLOSS'),
  ('PRF_POSTER_ACRYLSTK_MIRROR','COMP_POSTER_ACRYLSTK_MIRROR'),
  ('PRF_POSTER_MINI_STANDBOARD','COMP_POSTER_MINI_STANDBOARD'),
  ('PRF_POSTER_MINI_BANNER','COMP_POSTER_MINI_BANNER')
) AS v(frm_cd, comp_cd)
WHERE NOT EXISTS (SELECT 1 FROM t_prc_formula_components x WHERE x.frm_cd=v.frm_cd AND x.comp_cd=v.comp_cd);
