with vn(nm) as (values
($$사각손거울$$),
($$블랙사각손거울$$),
($$워터북보틀$$),
($$벨벳쿠션$$),
($$피크닉매트$$),
($$핀버튼$$),
($$레더스트랩키링$$),
($$키캡키링$$),
($$LED투명키캡키링$$),
($$클립보드$$),
($$투명클립보드$$),
($$만년스탬프$$),
($$폰스트랩$$),
($$아크릴쉐이커코롯토$$),
($$이미지피켓$$),
($$레더 플랫 파우치$$),
($$레더 슬림 파우치$$),
($$레더 삼각 파우치$$),
($$레더 볼륨 파우치$$),
($$레더 아이패드/노트북 파우치$$),
($$캔버스 플랫 파우치$$),
($$캔버스 삼각 파우치$$),
($$린넨 스트링 파우치$$),
($$타이벡 플랫 파우치$$),
($$타이벡 슬림 파우치$$),
($$타이벡 삼각 파우치$$),
($$타이벡 스트링 파우치$$),
($$메쉬슬림파우치$$),
($$레더 슬림 미니파우치$$),
($$레더 볼륨 미니파우치$$),
($$타이벡 양면 백팩$$),
($$타이벡보냉보틀백$$),
($$레더라벨제작$$),
($$슬림하드 폰케이스$$))
select coalesce(p.prd_cd,'(미등록)') prd_cd, vn.nm,
 coalesce((select count(*) from t_prd_product_price_formulas pf where pf.prd_cd=p.prd_cd),0) fml,
 coalesce((select count(*) from t_prd_product_prices pp where pp.prd_cd=p.prd_cd),0) dprice,
 coalesce((select count(*) from t_prd_product_option_groups og where og.prd_cd=p.prd_cd and og.del_yn='N'),0) optg,
 coalesce((select count(*) from t_prd_product_materials pm where pm.prd_cd=p.prd_cd and pm.del_yn='N'),0) actmat
from vn left join t_prd_products p on p.prd_nm=vn.nm and p.del_yn='N'
order by p.prd_cd nulls last;
