-- ============================================================
-- 00  사전 상태 검증 SELECT (READ-ONLY · 순수 SELECT · 쓰기 0)
-- 목적: COMMIT 전 필수 게이트 4종의 현행 라이브 실측.
--   ① 정본 9종 사전부재(혼재 0의 뿌리)  ② 멤버 comp formula 참조 현황
--   ③ 군별 nat_key(15열) 충돌 0(MC-02~09) / MC-01 S1_20P 내부 0
--   + MC-01 468행 halt 게이트 사전값 · 12 PRF 실재 · 공식별 현행배선(bystander)
-- 실행: psql -f 00-prestate-verify.sql  (BEGIN/ROLLBACK 불필요 — 조회만)
-- ============================================================
\pset footer off

-- ① 정본 9종 사전존재 여부 (행 0 = 통과. 하나라도 나오면 혼재 위험 → 중단 검토)
SELECT '① 정본 사전존재(행0기대)' gate, comp_cd, use_yn, del_yn
FROM t_prc_price_components
WHERE comp_cd IN ('COMP_PCB','COMP_NAMECARD_PREMIUM','COMP_NAMECARD_FOIL','COMP_NAMECARD_WHITE',
  'COMP_NAMECARD_STD','COMP_NAMECARD_COAT','COMP_NAMECARD_PEARL','COMP_NAMECARD_SHAPE','COMP_NAMECARD_MINISHAPE')
ORDER BY comp_cd;

-- 멤버 comp 카탈로그 현황
SELECT '멤버 comp 현황' info, comp_cd, use_yn, del_yn, prc_typ_cd
FROM t_prc_price_components
WHERE comp_cd IN (
 'COMP_NAMECARD_PREMIUM_S1_MGA','COMP_NAMECARD_PREMIUM_S1_MGB','COMP_NAMECARD_PREMIUM_S2_MGA','COMP_NAMECARD_PREMIUM_S2_MGB',
 'COMP_NAMECARD_FOIL_S1_STD','COMP_NAMECARD_FOIL_S1_HOLO','COMP_NAMECARD_FOIL_S2_STD','COMP_NAMECARD_FOIL_S2_HOLO',
 'COMP_NAMECARD_WHITE_S1W_CL','COMP_NAMECARD_WHITE_S1W_NOCL','COMP_NAMECARD_WHITE_S2W_CL','COMP_NAMECARD_WHITE_S2W_NOCL',
 'COMP_NAMECARD_STD_S1','COMP_NAMECARD_STD_S2','COMP_NAMECARD_COAT_S1','COMP_NAMECARD_COAT_S2',
 'COMP_NAMECARD_PEARL_S1','COMP_NAMECARD_PEARL_S2','COMP_NAMECARD_SHAPE_S1','COMP_NAMECARD_SHAPE_S2',
 'COMP_NAMECARD_MINISHAPE_S1','COMP_NAMECARD_MINISHAPE_S2',
 'COMP_PCB_S1_20P','COMP_PCB_S1_30P','COMP_PCB_S2_20P','COMP_PCB_S2_30P')
ORDER BY comp_cd;

-- 멤버별 단가행수 (이관 기대건수 대조: PREMIUM28·FOIL36·WHITE4·STD10·COAT4·PEARL8·SHAPE2·MINISHAPE2·PCB)
SELECT '멤버 단가행수' info, comp_cd, COUNT(*) rows
FROM t_prc_component_prices
WHERE comp_cd IN (
 'COMP_NAMECARD_PREMIUM_S1_MGA','COMP_NAMECARD_PREMIUM_S1_MGB','COMP_NAMECARD_PREMIUM_S2_MGA','COMP_NAMECARD_PREMIUM_S2_MGB',
 'COMP_NAMECARD_FOIL_S1_STD','COMP_NAMECARD_FOIL_S1_HOLO','COMP_NAMECARD_FOIL_S2_STD','COMP_NAMECARD_FOIL_S2_HOLO',
 'COMP_NAMECARD_WHITE_S1W_CL','COMP_NAMECARD_WHITE_S1W_NOCL','COMP_NAMECARD_WHITE_S2W_CL','COMP_NAMECARD_WHITE_S2W_NOCL',
 'COMP_NAMECARD_STD_S1','COMP_NAMECARD_STD_S2','COMP_NAMECARD_COAT_S1','COMP_NAMECARD_COAT_S2',
 'COMP_NAMECARD_PEARL_S1','COMP_NAMECARD_PEARL_S2','COMP_NAMECARD_SHAPE_S1','COMP_NAMECARD_SHAPE_S2',
 'COMP_NAMECARD_MINISHAPE_S1','COMP_NAMECARD_MINISHAPE_S2',
 'COMP_PCB_S1_20P','COMP_PCB_S1_30P','COMP_PCB_S2_20P','COMP_PCB_S2_30P')
GROUP BY comp_cd ORDER BY comp_cd;

-- ③ 군별 nat_key(15열) 충돌 사전실측 (MC-02~09 = 0 기대)
WITH allmembers AS (
  SELECT * FROM (VALUES
   ('MC-02','COMP_NAMECARD_PREMIUM_S1_MGA'),('MC-02','COMP_NAMECARD_PREMIUM_S1_MGB'),
   ('MC-02','COMP_NAMECARD_PREMIUM_S2_MGA'),('MC-02','COMP_NAMECARD_PREMIUM_S2_MGB'),
   ('MC-03','COMP_NAMECARD_FOIL_S1_STD'),('MC-03','COMP_NAMECARD_FOIL_S1_HOLO'),
   ('MC-03','COMP_NAMECARD_FOIL_S2_STD'),('MC-03','COMP_NAMECARD_FOIL_S2_HOLO'),
   ('MC-04','COMP_NAMECARD_WHITE_S1W_CL'),('MC-04','COMP_NAMECARD_WHITE_S1W_NOCL'),
   ('MC-04','COMP_NAMECARD_WHITE_S2W_CL'),('MC-04','COMP_NAMECARD_WHITE_S2W_NOCL'),
   ('MC-05','COMP_NAMECARD_STD_S1'),('MC-05','COMP_NAMECARD_STD_S2'),
   ('MC-06','COMP_NAMECARD_COAT_S1'),('MC-06','COMP_NAMECARD_COAT_S2'),
   ('MC-07','COMP_NAMECARD_PEARL_S1'),('MC-07','COMP_NAMECARD_PEARL_S2'),
   ('MC-08','COMP_NAMECARD_SHAPE_S1'),('MC-08','COMP_NAMECARD_SHAPE_S2'),
   ('MC-09','COMP_NAMECARD_MINISHAPE_S1'),('MC-09','COMP_NAMECARD_MINISHAPE_S2')
  ) AS t(grp,cc)
),
j AS (
  SELECT m.grp,
    (p.apply_ymd,p.siz_cd,p.plt_siz_cd,p.clr_cd,p.mat_cd,p.proc_cd,p.opt_cd,p.print_opt_cd,
     p.coat_side_cnt,p.bdl_qty,p.siz_width,p.siz_height,p.min_qty,COALESCE(p.dim_vals,'{}'::jsonb)::text) k
  FROM t_prc_component_prices p JOIN allmembers m ON p.comp_cd=m.cc
)
SELECT '③ nat_key 충돌(0기대)' gate, grp, COUNT(*) member_rows, COUNT(*)-COUNT(DISTINCT k) collisions
FROM j GROUP BY grp ORDER BY grp;

-- ② 멤버 comp formula 참조수 (재배선 前 현황 — 재배선 후 0 되어야 함)
SELECT '② 멤버 fc참조(재배선前)' gate, comp_cd, COUNT(*) fc_refs
FROM t_prc_formula_components
WHERE comp_cd IN (
 'COMP_NAMECARD_PREMIUM_S1_MGA','COMP_NAMECARD_PREMIUM_S1_MGB','COMP_NAMECARD_PREMIUM_S2_MGA','COMP_NAMECARD_PREMIUM_S2_MGB',
 'COMP_NAMECARD_FOIL_S1_STD','COMP_NAMECARD_FOIL_S1_HOLO','COMP_NAMECARD_FOIL_S2_STD','COMP_NAMECARD_FOIL_S2_HOLO',
 'COMP_NAMECARD_WHITE_S1W_CL','COMP_NAMECARD_WHITE_S1W_NOCL','COMP_NAMECARD_WHITE_S2W_CL','COMP_NAMECARD_WHITE_S2W_NOCL',
 'COMP_NAMECARD_STD_S1','COMP_NAMECARD_STD_S2','COMP_NAMECARD_COAT_S1','COMP_NAMECARD_COAT_S2',
 'COMP_NAMECARD_PEARL_S1','COMP_NAMECARD_PEARL_S2','COMP_NAMECARD_SHAPE_S1','COMP_NAMECARD_SHAPE_S2',
 'COMP_NAMECARD_MINISHAPE_S1','COMP_NAMECARD_MINISHAPE_S2',
 'COMP_PCB_S1_20P','COMP_PCB_S1_30P','COMP_PCB_S2_20P','COMP_PCB_S2_30P')
GROUP BY comp_cd ORDER BY comp_cd;

-- ★MC-01 특수: 468 halt 게이트 사전값
SELECT '★MC-01 S1_20P 행수(468기대)' gate, COUNT(*) rows, COUNT(DISTINCT (print_opt_cd,opt_cd)) combos
FROM t_prc_component_prices WHERE comp_cd='COMP_PCB_S1_20P';

-- 12 PRF 영향공식 실재 확인
SELECT '영향공식 실재(12기대)' info, frm_cd FROM t_prc_price_formulas
WHERE frm_cd IN ('PRF_PCB_FIXED','PRF_NAMECARD_PREMIUM','PRF_NAMECARD_PREMIUM_FOIL','PRF_NAMECARD_FOIL',
 'PRF_NAMECARD_WHITE','PRF_NAMECARD_FIXED','PRF_NAMECARD_FIXED_FOIL','PRF_NAMECARD_COAT',
 'PRF_NAMECARD_PEARL','PRF_NAMECARD_PEARL_FOIL','PRF_NAMECARD_SHAPE','PRF_NAMECARD_MINISHAPE')
ORDER BY frm_cd;

-- 공식별 현행배선 (정본 삽입 전 disp_seq·bystander 파악)
SELECT '공식별 현행배선' info, frm_cd, string_agg(comp_cd||':'||disp_seq, ', ' ORDER BY disp_seq) wiring
FROM t_prc_formula_components
WHERE frm_cd IN ('PRF_NAMECARD_PREMIUM','PRF_NAMECARD_PREMIUM_FOIL','PRF_NAMECARD_FOIL',
 'PRF_NAMECARD_WHITE','PRF_NAMECARD_FIXED','PRF_NAMECARD_FIXED_FOIL','PRF_NAMECARD_COAT',
 'PRF_NAMECARD_PEARL','PRF_NAMECARD_PEARL_FOIL','PRF_NAMECARD_SHAPE','PRF_NAMECARD_MINISHAPE','PRF_PCB_FIXED')
GROUP BY frm_cd ORDER BY frm_cd;
