-- UNDO: 밴드총액 교정 되돌리기(.02→.01). 백업=bandtotal-prctyp-undo-backup.csv
BEGIN;
UPDATE t_prc_price_components SET prc_typ_cd='PRICE_TYPE.01', upd_dt=now()
 WHERE comp_cd IN ('COMP_NAMECARD_STD_S1','COMP_NAMECARD_STD_S2','COMP_NAMECARD_PEARL_S1','COMP_NAMECARD_PEARL_S2',
 'COMP_NAMECARD_SHAPE_S1','COMP_NAMECARD_SHAPE_S2','COMP_NAMECARD_MINISHAPE_S1','COMP_NAMECARD_MINISHAPE_S2',
 'COMP_NAMECARD_FOIL_S1_STD','COMP_NAMECARD_CLEAR_S1','COMP_ENV_MAKING','COMP_GANGPAN_PRINT',
 'COMP_NAMECARD_FOIL_S2_STD','COMP_NAMECARD_FOIL_S1_HOLO','COMP_NAMECARD_FOIL_S2_HOLO','COMP_NAMECARD_COAT_S1',
 'COMP_NAMECARD_COAT_S2','COMP_NAMECARD_PREMIUM_S1_MGA','COMP_NAMECARD_PREMIUM_S1_MGB','COMP_NAMECARD_PREMIUM_S2_MGA',
 'COMP_NAMECARD_PREMIUM_S2_MGB','COMP_NAMECARD_WHITE_S1W_CL','COMP_NAMECARD_WHITE_S1W_NOCL','COMP_NAMECARD_WHITE_S2W_CL','COMP_NAMECARD_WHITE_S2W_NOCL');
-- COMMIT;  -- 검토 후 수동 해제
ROLLBACK;
