-- silsa siz_cd 오적재 교정: 단가행 siz_cd 중복본→정본 재키잉 (★COMMIT·인간 승인 2026-06-29)
-- 근본원인: 상품 옵션 siz_cd(정본 174/197/172/170/293) vs 본체 단가행 siz_cd(중복본 315/317/258/426/294) 불일치.
--   엔진 _row_matches(pricing.py:94)가 단가행 siz_cd를 매칭키로 사용(타 NON_QTY 차원 전부 NULL=와일드카드)
--   → 정본↔중복본 어긋나 매칭 0 → 견적 0. 물리 cut_width/height 5쌍 전부 동일(독립 검증).
-- 스코프: silsa PRICED-0 본체 comp 9종 한정(전부 1상품 전용·타군 영향 0·충돌 0 검증 완료).
-- 값(unit_price 등) 불변 — siz_cd 만 정본화. 마스터(t_siz_sizes) 미터치. UNDO=silsa-sizcd-rekey-260629-UNDO.sql.
BEGIN;

UPDATE t_prc_component_prices SET siz_cd='SIZ_000174', upd_dt=now()
 WHERE siz_cd='SIZ_000315' AND comp_cd IN (
   'COMP_POSTER_FOAMBOARD_WHITE','COMP_POSTER_FOMEXBOARD_WHITE3MM','COMP_POSTER_FRAMELESS_WOOD',
   'COMP_POSTER_LEATHER_FRAME','COMP_POSTER_CANVAS_HANGING','COMP_POSTER_JOKJA',
   'COMP_POSTER_SHEETCUT_MATTE','COMP_POSTER_SHEETCUT_HOLO','COMP_POSTER_MINI_STANDBOARD');

UPDATE t_prc_component_prices SET siz_cd='SIZ_000197', upd_dt=now()
 WHERE siz_cd='SIZ_000317' AND comp_cd IN (
   'COMP_POSTER_FOAMBOARD_WHITE','COMP_POSTER_FOMEXBOARD_WHITE3MM','COMP_POSTER_FRAMELESS_WOOD',
   'COMP_POSTER_LEATHER_FRAME','COMP_POSTER_CANVAS_HANGING','COMP_POSTER_JOKJA',
   'COMP_POSTER_SHEETCUT_MATTE','COMP_POSTER_SHEETCUT_HOLO','COMP_POSTER_MINI_STANDBOARD');

UPDATE t_prc_component_prices SET siz_cd='SIZ_000172', upd_dt=now()
 WHERE siz_cd='SIZ_000258' AND comp_cd IN (
   'COMP_POSTER_FOAMBOARD_WHITE','COMP_POSTER_FOMEXBOARD_WHITE3MM','COMP_POSTER_FRAMELESS_WOOD',
   'COMP_POSTER_LEATHER_FRAME','COMP_POSTER_CANVAS_HANGING','COMP_POSTER_JOKJA',
   'COMP_POSTER_SHEETCUT_MATTE','COMP_POSTER_SHEETCUT_HOLO','COMP_POSTER_MINI_STANDBOARD');

UPDATE t_prc_component_prices SET siz_cd='SIZ_000170', upd_dt=now()
 WHERE siz_cd='SIZ_000426' AND comp_cd IN (
   'COMP_POSTER_FOAMBOARD_WHITE','COMP_POSTER_FOMEXBOARD_WHITE3MM','COMP_POSTER_FRAMELESS_WOOD',
   'COMP_POSTER_LEATHER_FRAME','COMP_POSTER_CANVAS_HANGING','COMP_POSTER_JOKJA',
   'COMP_POSTER_SHEETCUT_MATTE','COMP_POSTER_SHEETCUT_HOLO','COMP_POSTER_MINI_STANDBOARD');

UPDATE t_prc_component_prices SET siz_cd='SIZ_000293', upd_dt=now()
 WHERE siz_cd='SIZ_000294' AND comp_cd IN (
   'COMP_POSTER_FOAMBOARD_WHITE','COMP_POSTER_FOMEXBOARD_WHITE3MM','COMP_POSTER_FRAMELESS_WOOD',
   'COMP_POSTER_LEATHER_FRAME','COMP_POSTER_CANVAS_HANGING','COMP_POSTER_JOKJA',
   'COMP_POSTER_SHEETCUT_MATTE','COMP_POSTER_SHEETCUT_HOLO','COMP_POSTER_MINI_STANDBOARD');

COMMIT;
