-- 01_update_notes.sql — 전 상품군 가격테이블 note 전문용어→쉬운 한국어 교정 (note 컬럼만)
-- 생성기: gen_notes.py (손편집 금지·재현성). 멱등=IS DISTINCT FROM + no-op regexp.
-- [HARD] unit_price·prc_typ_cd·축 컬럼 절대 미변경. SET 절은 note·upd_dt 둘뿐.
-- 016 사슬 행은 이미 교정됨 → 동일 텍스트면 IS DISTINCT FROM 가드로 자동 no-op(중복 안전).

-- A) 구성요소 정의행 t_prc_price_components.note (comp_cd PK)
UPDATE t_prc_price_components SET note='투명 아크릴 1.5T 인쇄·가공 포함가. 사이즈·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_ACRYL_CLEAR15T' AND note IS DISTINCT FROM '투명 아크릴 1.5T 인쇄·가공 포함가. 사이즈·수량별 단가표.';
UPDATE t_prc_price_components SET note='투명 아크릴 3T 인쇄·가공 포함가. 사이즈·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_ACRYL_CLEAR3T' AND note IS DISTINCT FROM '투명 아크릴 3T 인쇄·가공 포함가. 사이즈·수량별 단가표.';
UPDATE t_prc_price_components SET note='미러 아크릴 3T 인쇄·가공 포함가. 사이즈·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_ACRYL_MIRROR3T' AND note IS DISTINCT FROM '미러 아크릴 3T 인쇄·가공 포함가. 사이즈·수량별 단가표.';
UPDATE t_prc_price_components SET note='제본 가공비(후가공). 제본 종류·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_BIND_CAL_DESK130' AND note IS DISTINCT FROM '제본 가공비(후가공). 제본 종류·수량별 단가표.';
UPDATE t_prc_price_components SET note='제본 가공비(후가공). 제본 종류·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_BIND_CAL_DESK220' AND note IS DISTINCT FROM '제본 가공비(후가공). 제본 종류·수량별 단가표.';
UPDATE t_prc_price_components SET note='제본 가공비(후가공). 제본 종류·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_BIND_CAL_DESKMINI' AND note IS DISTINCT FROM '제본 가공비(후가공). 제본 종류·수량별 단가표.';
UPDATE t_prc_price_components SET note='제본 가공비(후가공). 제본 종류·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_BIND_CAL_WALL' AND note IS DISTINCT FROM '제본 가공비(후가공). 제본 종류·수량별 단가표.';
UPDATE t_prc_price_components SET note='제본 가공비(후가공). 제본 종류·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_BIND_HC_MUSEON' AND note IS DISTINCT FROM '제본 가공비(후가공). 제본 종류·수량별 단가표.';
UPDATE t_prc_price_components SET note='제본 가공비(후가공). 제본 종류·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_BIND_HC_TWINRING' AND note IS DISTINCT FROM '제본 가공비(후가공). 제본 종류·수량별 단가표.';
UPDATE t_prc_price_components SET note='제본 가공비(후가공). 제본 종류·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_BIND_JUNGCHEOL' AND note IS DISTINCT FROM '제본 가공비(후가공). 제본 종류·수량별 단가표.';
UPDATE t_prc_price_components SET note='제본 가공비(후가공). 제본 종류·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_BIND_MUSEON' AND note IS DISTINCT FROM '제본 가공비(후가공). 제본 종류·수량별 단가표.';
UPDATE t_prc_price_components SET note='제본 가공비(후가공). 제본 종류·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_BIND_PUR' AND note IS DISTINCT FROM '제본 가공비(후가공). 제본 종류·수량별 단가표.';
UPDATE t_prc_price_components SET note='제본 가공비(후가공). 제본 종류·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_BIND_SSABARI' AND note IS DISTINCT FROM '제본 가공비(후가공). 제본 종류·수량별 단가표.';
UPDATE t_prc_price_components SET note='제본 가공비(후가공). 제본 종류·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_BIND_TWINRING' AND note IS DISTINCT FROM '제본 가공비(후가공). 제본 종류·수량별 단가표.';
UPDATE t_prc_price_components SET note='커팅(완칼/미싱) 포함 완제품가. 소재·사이즈·수량을 합산한 1장당 단가표.', upd_dt=now() WHERE comp_cd='COMP_CUT_FULL_DIECUT' AND note IS DISTINCT FROM '커팅(완칼/미싱) 포함 완제품가. 소재·사이즈·수량을 합산한 1장당 단가표.';
UPDATE t_prc_price_components SET note='커팅(완칼/미싱) 포함 완제품가. 소재·사이즈·수량을 합산한 1장당 단가표.', upd_dt=now() WHERE comp_cd='COMP_CUT_FULL_PERF_1H6' AND note IS DISTINCT FROM '커팅(완칼/미싱) 포함 완제품가. 소재·사이즈·수량을 합산한 1장당 단가표.';
UPDATE t_prc_price_components SET note='커팅(완칼/미싱) 포함 완제품가. 소재·사이즈·수량을 합산한 1장당 단가표.', upd_dt=now() WHERE comp_cd='COMP_CUT_FULL_PERF_2H6' AND note IS DISTINCT FROM '커팅(완칼/미싱) 포함 완제품가. 소재·사이즈·수량을 합산한 1장당 단가표.';
UPDATE t_prc_price_components SET note='타공(구멍 뚫기) 가공비(후가공). 구 수·출력매수별 단가표.', upd_dt=now() WHERE comp_cd='COMP_CUT_PERF_1H6' AND note IS DISTINCT FROM '타공(구멍 뚫기) 가공비(후가공). 구 수·출력매수별 단가표.';
UPDATE t_prc_price_components SET note='봉투 제작 완제품가(용지 포함). 봉투 종류·소재·주문수량 구간별 단가표.', upd_dt=now() WHERE comp_cd='COMP_ENV_MAKING' AND note IS DISTINCT FROM '봉투 제작 완제품가(용지 포함). 봉투 종류·소재·주문수량 구간별 단가표.';
UPDATE t_prc_price_components SET note='접지(접는 가공)비(후가공). 접지 종류·주문수량 구간별 작업 1건 고정 금액(수량을 곱하지 않음).', upd_dt=now() WHERE comp_cd='COMP_FOLD_CARD_2H' AND note IS DISTINCT FROM '접지(접는 가공)비(후가공). 접지 종류·주문수량 구간별 작업 1건 고정 금액(수량을 곱하지 않음).';
UPDATE t_prc_price_components SET note='접지(접는 가공)비(후가공). 접지 종류·주문수량 구간별 작업 1건 고정 금액(수량을 곱하지 않음).', upd_dt=now() WHERE comp_cd='COMP_FOLD_CARD_3H' AND note IS DISTINCT FROM '접지(접는 가공)비(후가공). 접지 종류·주문수량 구간별 작업 1건 고정 금액(수량을 곱하지 않음).';
UPDATE t_prc_price_components SET note='접지(접는 가공)비(후가공). 접지 종류·주문수량 구간별 작업 1건 고정 금액(수량을 곱하지 않음).', upd_dt=now() WHERE comp_cd='COMP_FOLD_CARD_6CR' AND note IS DISTINCT FROM '접지(접는 가공)비(후가공). 접지 종류·주문수량 구간별 작업 1건 고정 금액(수량을 곱하지 않음).';
UPDATE t_prc_price_components SET note='접지(접는 가공)비(후가공). 접지 종류·주문수량 구간별 작업 1건 고정 금액(수량을 곱하지 않음).', upd_dt=now() WHERE comp_cd='COMP_FOLD_LEAF_3FOLD' AND note IS DISTINCT FROM '접지(접는 가공)비(후가공). 접지 종류·주문수량 구간별 작업 1건 고정 금액(수량을 곱하지 않음).';
UPDATE t_prc_price_components SET note='접지(접는 가공)비(후가공). 접지 종류·주문수량 구간별 작업 1건 고정 금액(수량을 곱하지 않음).', upd_dt=now() WHERE comp_cd='COMP_FOLD_LEAF_4ACC' AND note IS DISTINCT FROM '접지(접는 가공)비(후가공). 접지 종류·주문수량 구간별 작업 1건 고정 금액(수량을 곱하지 않음).';
UPDATE t_prc_price_components SET note='접지(접는 가공)비(후가공). 접지 종류·주문수량 구간별 작업 1건 고정 금액(수량을 곱하지 않음).', upd_dt=now() WHERE comp_cd='COMP_FOLD_LEAF_4GATE' AND note IS DISTINCT FROM '접지(접는 가공)비(후가공). 접지 종류·주문수량 구간별 작업 1건 고정 금액(수량을 곱하지 않음).';
UPDATE t_prc_price_components SET note='접지(접는 가공)비(후가공). 접지 종류·주문수량 구간별 작업 1건 고정 금액(수량을 곱하지 않음).', upd_dt=now() WHERE comp_cd='COMP_FOLD_LEAF_HALF' AND note IS DISTINCT FROM '접지(접는 가공)비(후가공). 접지 종류·주문수량 구간별 작업 1건 고정 금액(수량을 곱하지 않음).';
UPDATE t_prc_price_components SET note='합판 도무송(목형 따기) 완제품가. 사이즈·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_GANGPAN_PRINT' AND note IS DISTINCT FROM '합판 도무송(목형 따기) 완제품가. 사이즈·수량별 단가표.';
UPDATE t_prc_price_components SET note='명함 완제품가(용지 포함). 소재·인쇄면·수량을 합산한 1건당 단가표.', upd_dt=now() WHERE comp_cd='COMP_NAMECARD_CLEAR_S1' AND note IS DISTINCT FROM '명함 완제품가(용지 포함). 소재·인쇄면·수량을 합산한 1건당 단가표.';
UPDATE t_prc_price_components SET note='명함 완제품가(용지 포함). 소재·인쇄면·수량을 합산한 1건당 단가표.', upd_dt=now() WHERE comp_cd='COMP_NAMECARD_COAT_S1' AND note IS DISTINCT FROM '명함 완제품가(용지 포함). 소재·인쇄면·수량을 합산한 1건당 단가표.';
UPDATE t_prc_price_components SET note='명함 완제품가(용지 포함). 소재·인쇄면·수량을 합산한 1건당 단가표.', upd_dt=now() WHERE comp_cd='COMP_NAMECARD_COAT_S2' AND note IS DISTINCT FROM '명함 완제품가(용지 포함). 소재·인쇄면·수량을 합산한 1건당 단가표.';
UPDATE t_prc_price_components SET note='오리지널 박명함 완제품가(종이+동판+박 가공 합산). 인쇄면·박 종류·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_NAMECARD_FOIL_S1_HOLO' AND note IS DISTINCT FROM '오리지널 박명함 완제품가(종이+동판+박 가공 합산). 인쇄면·박 종류·수량별 단가표.';
UPDATE t_prc_price_components SET note='오리지널 박명함 완제품가(종이+동판+박 가공 합산). 인쇄면·박 종류·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_NAMECARD_FOIL_S1_STD' AND note IS DISTINCT FROM '오리지널 박명함 완제품가(종이+동판+박 가공 합산). 인쇄면·박 종류·수량별 단가표.';
UPDATE t_prc_price_components SET note='오리지널 박명함 완제품가(종이+동판+박 가공 합산). 인쇄면·박 종류·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_NAMECARD_FOIL_S2_HOLO' AND note IS DISTINCT FROM '오리지널 박명함 완제품가(종이+동판+박 가공 합산). 인쇄면·박 종류·수량별 단가표.';
UPDATE t_prc_price_components SET note='오리지널 박명함 완제품가(종이+동판+박 가공 합산). 인쇄면·박 종류·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_NAMECARD_FOIL_S2_STD' AND note IS DISTINCT FROM '오리지널 박명함 완제품가(종이+동판+박 가공 합산). 인쇄면·박 종류·수량별 단가표.';
UPDATE t_prc_price_components SET note='박·형압용 동판 셋업비. 주문 1건당 한 번 부과(수량을 곱하지 않음).', upd_dt=now() WHERE comp_cd='COMP_NAMECARD_FOIL_SETUP_S1_STD' AND note IS DISTINCT FROM '박·형압용 동판 셋업비. 주문 1건당 한 번 부과(수량을 곱하지 않음).';
UPDATE t_prc_price_components SET note='박·형압용 동판 셋업비. 주문 1건당 한 번 부과(수량을 곱하지 않음).', upd_dt=now() WHERE comp_cd='COMP_NAMECARD_FOIL_SETUP_S2_STD' AND note IS DISTINCT FROM '박·형압용 동판 셋업비. 주문 1건당 한 번 부과(수량을 곱하지 않음).';
UPDATE t_prc_price_components SET note='명함 완제품가(용지 포함). 소재·인쇄면·수량을 합산한 1건당 단가표.', upd_dt=now() WHERE comp_cd='COMP_NAMECARD_MINISHAPE_S1' AND note IS DISTINCT FROM '명함 완제품가(용지 포함). 소재·인쇄면·수량을 합산한 1건당 단가표.';
UPDATE t_prc_price_components SET note='명함 완제품가(용지 포함). 소재·인쇄면·수량을 합산한 1건당 단가표.', upd_dt=now() WHERE comp_cd='COMP_NAMECARD_MINISHAPE_S2' AND note IS DISTINCT FROM '명함 완제품가(용지 포함). 소재·인쇄면·수량을 합산한 1건당 단가표.';
UPDATE t_prc_price_components SET note='명함 완제품가(용지 포함). 소재·인쇄면·수량을 합산한 1건당 단가표.', upd_dt=now() WHERE comp_cd='COMP_NAMECARD_PEARL_S1' AND note IS DISTINCT FROM '명함 완제품가(용지 포함). 소재·인쇄면·수량을 합산한 1건당 단가표.';
UPDATE t_prc_price_components SET note='명함 완제품가(용지 포함). 소재·인쇄면·수량을 합산한 1건당 단가표.', upd_dt=now() WHERE comp_cd='COMP_NAMECARD_PEARL_S2' AND note IS DISTINCT FROM '명함 완제품가(용지 포함). 소재·인쇄면·수량을 합산한 1건당 단가표.';
UPDATE t_prc_price_components SET note='명함 완제품가(용지 포함). 소재·인쇄면·수량을 합산한 1건당 단가표.', upd_dt=now() WHERE comp_cd='COMP_NAMECARD_PREMIUM_S1_MGA' AND note IS DISTINCT FROM '명함 완제품가(용지 포함). 소재·인쇄면·수량을 합산한 1건당 단가표.';
UPDATE t_prc_price_components SET note='명함 완제품가(용지 포함). 소재·인쇄면·수량을 합산한 1건당 단가표.', upd_dt=now() WHERE comp_cd='COMP_NAMECARD_PREMIUM_S1_MGB' AND note IS DISTINCT FROM '명함 완제품가(용지 포함). 소재·인쇄면·수량을 합산한 1건당 단가표.';
UPDATE t_prc_price_components SET note='명함 완제품가(용지 포함). 소재·인쇄면·수량을 합산한 1건당 단가표.', upd_dt=now() WHERE comp_cd='COMP_NAMECARD_PREMIUM_S2_MGA' AND note IS DISTINCT FROM '명함 완제품가(용지 포함). 소재·인쇄면·수량을 합산한 1건당 단가표.';
UPDATE t_prc_price_components SET note='명함 완제품가(용지 포함). 소재·인쇄면·수량을 합산한 1건당 단가표.', upd_dt=now() WHERE comp_cd='COMP_NAMECARD_PREMIUM_S2_MGB' AND note IS DISTINCT FROM '명함 완제품가(용지 포함). 소재·인쇄면·수량을 합산한 1건당 단가표.';
UPDATE t_prc_price_components SET note='명함 완제품가(용지 포함). 소재·인쇄면·수량을 합산한 1건당 단가표.', upd_dt=now() WHERE comp_cd='COMP_NAMECARD_SHAPE_S1' AND note IS DISTINCT FROM '명함 완제품가(용지 포함). 소재·인쇄면·수량을 합산한 1건당 단가표.';
UPDATE t_prc_price_components SET note='명함 완제품가(용지 포함). 소재·인쇄면·수량을 합산한 1건당 단가표.', upd_dt=now() WHERE comp_cd='COMP_NAMECARD_SHAPE_S2' AND note IS DISTINCT FROM '명함 완제품가(용지 포함). 소재·인쇄면·수량을 합산한 1건당 단가표.';
UPDATE t_prc_price_components SET note='명함 완제품가(용지 포함). 소재·인쇄면·수량을 합산한 1건당 단가표.', upd_dt=now() WHERE comp_cd='COMP_NAMECARD_STD_S1' AND note IS DISTINCT FROM '명함 완제품가(용지 포함). 소재·인쇄면·수량을 합산한 1건당 단가표.';
UPDATE t_prc_price_components SET note='명함 완제품가(용지 포함). 소재·인쇄면·수량을 합산한 1건당 단가표.', upd_dt=now() WHERE comp_cd='COMP_NAMECARD_STD_S2' AND note IS DISTINCT FROM '명함 완제품가(용지 포함). 소재·인쇄면·수량을 합산한 1건당 단가표.';
UPDATE t_prc_price_components SET note='명함 완제품가(용지 포함). 소재·인쇄면·수량을 합산한 1건당 단가표.', upd_dt=now() WHERE comp_cd='COMP_NAMECARD_WHITE_S1W_CL' AND note IS DISTINCT FROM '명함 완제품가(용지 포함). 소재·인쇄면·수량을 합산한 1건당 단가표.';
UPDATE t_prc_price_components SET note='명함 완제품가(용지 포함). 소재·인쇄면·수량을 합산한 1건당 단가표.', upd_dt=now() WHERE comp_cd='COMP_NAMECARD_WHITE_S1W_NOCL' AND note IS DISTINCT FROM '명함 완제품가(용지 포함). 소재·인쇄면·수량을 합산한 1건당 단가표.';
UPDATE t_prc_price_components SET note='명함 완제품가(용지 포함). 소재·인쇄면·수량을 합산한 1건당 단가표.', upd_dt=now() WHERE comp_cd='COMP_NAMECARD_WHITE_S2W_CL' AND note IS DISTINCT FROM '명함 완제품가(용지 포함). 소재·인쇄면·수량을 합산한 1건당 단가표.';
UPDATE t_prc_price_components SET note='명함 완제품가(용지 포함). 소재·인쇄면·수량을 합산한 1건당 단가표.', upd_dt=now() WHERE comp_cd='COMP_NAMECARD_WHITE_S2W_NOCL' AND note IS DISTINCT FROM '명함 완제품가(용지 포함). 소재·인쇄면·수량을 합산한 1건당 단가표.';
UPDATE t_prc_price_components SET note='엽서북 완제품가. 인쇄면·페이지수·수량별 1권당 단가표.', upd_dt=now() WHERE comp_cd='COMP_PCB_S1_20P' AND note IS DISTINCT FROM '엽서북 완제품가. 인쇄면·페이지수·수량별 1권당 단가표.';
UPDATE t_prc_price_components SET note='엽서북 완제품가. 인쇄면·페이지수·수량별 1권당 단가표.', upd_dt=now() WHERE comp_cd='COMP_PCB_S1_30P' AND note IS DISTINCT FROM '엽서북 완제품가. 인쇄면·페이지수·수량별 1권당 단가표.';
UPDATE t_prc_price_components SET note='엽서북 완제품가. 인쇄면·페이지수·수량별 1권당 단가표.', upd_dt=now() WHERE comp_cd='COMP_PCB_S2_20P' AND note IS DISTINCT FROM '엽서북 완제품가. 인쇄면·페이지수·수량별 1권당 단가표.';
UPDATE t_prc_price_components SET note='엽서북 완제품가. 인쇄면·페이지수·수량별 1권당 단가표.', upd_dt=now() WHERE comp_cd='COMP_PCB_S2_30P' AND note IS DISTINCT FROM '엽서북 완제품가. 인쇄면·페이지수·수량별 1권당 단가표.';
UPDATE t_prc_price_components SET note='포토카드 완제품가. 구성·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_PHOTOCARD_BULK' AND note IS DISTINCT FROM '포토카드 완제품가. 구성·수량별 단가표.';
UPDATE t_prc_price_components SET note='포토카드 완제품가. 구성·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_PHOTOCARD_CLEAR_SET' AND note IS DISTINCT FROM '포토카드 완제품가. 구성·수량별 단가표.';
UPDATE t_prc_price_components SET note='포토카드 완제품가. 구성·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_PHOTOCARD_SET' AND note IS DISTINCT FROM '포토카드 완제품가. 구성·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 추가옵션 가격(거치대·끈·타공 등 별도 추가). 옵션·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POPT_BNR_GAKMOK_STR_900_4' AND note IS DISTINCT FROM '포스터·사인 추가옵션 가격(거치대·끈·타공 등 별도 추가). 옵션·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 추가옵션 가격(거치대·끈·타공 등 별도 추가). 옵션·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POPT_BNR_GAKMOK_STR_900_4_GT' AND note IS DISTINCT FROM '포스터·사인 추가옵션 가격(거치대·끈·타공 등 별도 추가). 옵션·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 추가옵션 가격(거치대·끈·타공 등 별도 추가). 옵션·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POPT_BNR_GAKMOK_STR_900_4_LE' AND note IS DISTINCT FROM '포스터·사인 추가옵션 가격(거치대·끈·타공 등 별도 추가). 옵션·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTER_ACRYLSTK_GLOSS' AND note IS DISTINCT FROM '포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTER_ACRYLSTK_MIRROR' AND note IS DISTINCT FROM '포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTER_ADH_CLEAR_PVC' AND note IS DISTINCT FROM '포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTER_ADH_WATERPROOF_PVC' AND note IS DISTINCT FROM '포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTER_ARTFABRIC_GRAPHIC' AND note IS DISTINCT FROM '포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTER_ARTPAPER_MATTE' AND note IS DISTINCT FROM '포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTER_ARTPRINT_PHOTO' AND note IS DISTINCT FROM '포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTER_BANNER_MESH' AND note IS DISTINCT FROM '포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTER_BANNER_NORMAL' AND note IS DISTINCT FROM '포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTER_CANVAS_FABRIC' AND note IS DISTINCT FROM '포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTER_CANVAS_HANGING' AND note IS DISTINCT FROM '포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTER_FOAMBOARD_BLACK' AND note IS DISTINCT FROM '포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTER_FOAMBOARD_WHITE' AND note IS DISTINCT FROM '포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTER_FOMEXBOARD_WHITE3MM' AND note IS DISTINCT FROM '포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTER_FOMEXBOARD_WHITE5MM' AND note IS DISTINCT FROM '포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTER_FRAMELESS_WOOD' AND note IS DISTINCT FROM '포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTER_JOKJA' AND note IS DISTINCT FROM '포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTER_LEATHER_ARTPRINT' AND note IS DISTINCT FROM '포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTER_LEATHER_FRAME' AND note IS DISTINCT FROM '포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTER_LINEN_FABRIC' AND note IS DISTINCT FROM '포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTER_LINEN_WOODBONG' AND note IS DISTINCT FROM '포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTER_MESH_BANNER' AND note IS DISTINCT FROM '포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTER_MESH_PRINT' AND note IS DISTINCT FROM '포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTER_MINI_BANNER' AND note IS DISTINCT FROM '포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTER_MINI_STANDBOARD' AND note IS DISTINCT FROM '포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 추가옵션 가격(거치대·끈·타공 등 별도 추가). 옵션·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTEROPT_BANNER_MESH_ADD_QBANG_4' AND note IS DISTINCT FROM '포스터·사인 추가옵션 가격(거치대·끈·타공 등 별도 추가). 옵션·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 추가옵션 가격(거치대·끈·타공 등 별도 추가). 옵션·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTEROPT_BANNER_MESH_ADD_STRING_4' AND note IS DISTINCT FROM '포스터·사인 추가옵션 가격(거치대·끈·타공 등 별도 추가). 옵션·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 추가옵션 가격(거치대·끈·타공 등 별도 추가). 옵션·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTEROPT_BANNER_MESH_PROC_OPT' AND note IS DISTINCT FROM '포스터·사인 추가옵션 가격(거치대·끈·타공 등 별도 추가). 옵션·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 추가옵션 가격(거치대·끈·타공 등 별도 추가). 옵션·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTEROPT_BANNER_MESH_PROC_PUNCH_4' AND note IS DISTINCT FROM '포스터·사인 추가옵션 가격(거치대·끈·타공 등 별도 추가). 옵션·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 추가옵션 가격(거치대·끈·타공 등 별도 추가). 옵션·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTEROPT_BANNER_MESH_PROC_PUNCH_6' AND note IS DISTINCT FROM '포스터·사인 추가옵션 가격(거치대·끈·타공 등 별도 추가). 옵션·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 추가옵션 가격(거치대·끈·타공 등 별도 추가). 옵션·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTEROPT_BANNER_MESH_PROC_PUNCH_8' AND note IS DISTINCT FROM '포스터·사인 추가옵션 가격(거치대·끈·타공 등 별도 추가). 옵션·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 추가옵션 가격(거치대·끈·타공 등 별도 추가). 옵션·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTEROPT_BANNER_NORMAL_ADD_QBANG_4' AND note IS DISTINCT FROM '포스터·사인 추가옵션 가격(거치대·끈·타공 등 별도 추가). 옵션·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 추가옵션 가격(거치대·끈·타공 등 별도 추가). 옵션·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTEROPT_BANNER_NORMAL_ADD_STRING_4' AND note IS DISTINCT FROM '포스터·사인 추가옵션 가격(거치대·끈·타공 등 별도 추가). 옵션·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 추가옵션 가격(거치대·끈·타공 등 별도 추가). 옵션·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTEROPT_BANNER_NORMAL_PROC_BONGSEW' AND note IS DISTINCT FROM '포스터·사인 추가옵션 가격(거치대·끈·타공 등 별도 추가). 옵션·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 추가옵션 가격(거치대·끈·타공 등 별도 추가). 옵션·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTEROPT_BANNER_NORMAL_PROC_CUTEDGE' AND note IS DISTINCT FROM '포스터·사인 추가옵션 가격(거치대·끈·타공 등 별도 추가). 옵션·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 추가옵션 가격(거치대·끈·타공 등 별도 추가). 옵션·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTEROPT_BANNER_NORMAL_PROC_DTAPE' AND note IS DISTINCT FROM '포스터·사인 추가옵션 가격(거치대·끈·타공 등 별도 추가). 옵션·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 추가옵션 가격(거치대·끈·타공 등 별도 추가). 옵션·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTEROPT_BANNER_NORMAL_PROC_PUNCH_4' AND note IS DISTINCT FROM '포스터·사인 추가옵션 가격(거치대·끈·타공 등 별도 추가). 옵션·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 추가옵션 가격(거치대·끈·타공 등 별도 추가). 옵션·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTEROPT_BANNER_NORMAL_PROC_PUNCH_6' AND note IS DISTINCT FROM '포스터·사인 추가옵션 가격(거치대·끈·타공 등 별도 추가). 옵션·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 추가옵션 가격(거치대·끈·타공 등 별도 추가). 옵션·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTEROPT_BANNER_NORMAL_PROC_PUNCH_8' AND note IS DISTINCT FROM '포스터·사인 추가옵션 가격(거치대·끈·타공 등 별도 추가). 옵션·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 추가옵션 가격(거치대·끈·타공 등 별도 추가). 옵션·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTEROPT_CANVAS_HANGING_WOODHANGER' AND note IS DISTINCT FROM '포스터·사인 추가옵션 가격(거치대·끈·타공 등 별도 추가). 옵션·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 추가옵션 가격(거치대·끈·타공 등 별도 추가). 옵션·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTEROPT_JOKJA_CEILHOOK' AND note IS DISTINCT FROM '포스터·사인 추가옵션 가격(거치대·끈·타공 등 별도 추가). 옵션·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 추가옵션 가격(거치대·끈·타공 등 별도 추가). 옵션·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTEROPT_LINEN_WOODBONG_WOODBONG' AND note IS DISTINCT FROM '포스터·사인 추가옵션 가격(거치대·끈·타공 등 별도 추가). 옵션·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 추가옵션 가격(거치대·끈·타공 등 별도 추가). 옵션·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTEROPT_PET_BANNER_STAND_IN' AND note IS DISTINCT FROM '포스터·사인 추가옵션 가격(거치대·끈·타공 등 별도 추가). 옵션·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 추가옵션 가격(거치대·끈·타공 등 별도 추가). 옵션·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTEROPT_PET_BANNER_STAND_OUT_S1' AND note IS DISTINCT FROM '포스터·사인 추가옵션 가격(거치대·끈·타공 등 별도 추가). 옵션·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 추가옵션 가격(거치대·끈·타공 등 별도 추가). 옵션·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTEROPT_PET_BANNER_STAND_OUT_S2' AND note IS DISTINCT FROM '포스터·사인 추가옵션 가격(거치대·끈·타공 등 별도 추가). 옵션·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTER_PET_BANNER' AND note IS DISTINCT FROM '포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTER_SHEETCUT_HOLO' AND note IS DISTINCT FROM '포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTER_SHEETCUT_MATTE' AND note IS DISTINCT FROM '포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTER_TYVEK_PRINT' AND note IS DISTINCT FROM '포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.';
UPDATE t_prc_price_components SET note='포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_POSTER_WATERPROOF_PET' AND note IS DISTINCT FROM '포스터·사인 완제품가(소재+출력+가공 포함 통가격). 사이즈·수량별 단가표.';
UPDATE t_prc_price_components SET note='스티커 완제품가(출력+가공 포함). 소재·사이즈·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_STK_PACK' AND note IS DISTINCT FROM '스티커 완제품가(출력+가공 포함). 소재·사이즈·수량별 단가표.';
UPDATE t_prc_price_components SET note='스티커 완제품가(출력+가공 포함). 소재·사이즈·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_STK_PRINT' AND note IS DISTINCT FROM '스티커 완제품가(출력+가공 포함). 소재·사이즈·수량별 단가표.';
UPDATE t_prc_price_components SET note='떡메모지 완제품가. 사이즈·권당 장수·수량별 단가표.', upd_dt=now() WHERE comp_cd='COMP_TTEOKME' AND note IS DISTINCT FROM '떡메모지 완제품가. 사이즈·권당 장수·수량별 단가표.';

-- B) 단가행 t_prc_component_prices.note — 결정적 regexp 치환 체인
--    합가 메모 → '작업 1건 고정 금액' / prefix [siz..] 제거 / 메모 시그니처 괄호 제거
--    [..mat=MAT_N..] 코드만 제거(설명 보존) / 'A≥N'→'A N 이상' / 잔여 ≥ → '이상' / 공백 정리
--    의미(소재·색·도수·사이즈) 괄호·[..포함가]·[묶음..]은 보존. note만 읽어 note만 씀.
UPDATE t_prc_component_prices cp SET note = btrim(regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(note, '\s*\([^()]*합가[^()]*(\([^()]*\)[^()]*)*\)', ' / 작업 1건 고정 금액(수량을 곱하지 않음)', 'g'), '^\[siz[^\]]*\]\s*', ''), '\s*\([^()]*(comp흡수|comp_typ|SIZ_[0-9]|MAT_[0-9]|PRD_[0-9]|규칙④|규칙[0-9]|bdl_qty|min_qty|라이브 siz|완제품비\.|완제품가 \.|중첩서브제품|소재묶음|band=|M-[0-9]+정정|행[0-9]|별도 add-on|수량무관 셋업|차원부재|DIRECT매칭|SIZ_PENDING|대표mat|규격단독|상품구분축|후니확인|=comp|추출결함|면당EA)[^()]*(\([^()]*\)[^()]*)*\)', '', 'g'), '\[([^\]]*?)\s*,?\s*mat=MAT_[0-9]+[^\]]*\]', '[\1]', 'g'), '(총제작수량|제작수량|출력매수|수량|장수)≥([0-9]+)', '\1 \2 이상', 'g'), '≥\s*([0-9]+)', '\1 이상', 'g'), '\s{2,}', ' ', 'g')), upd_dt=now()
WHERE cp.note IS NOT NULL
  AND cp.note ~ 'siz-corrected|comp_typ|PRC_COMPONENT_TYPE|round-2|clr=NULL|별색=공정|옵션=comp흡수|SIZ_[0-9]|MAT_[0-9]|PROC_[0-9]|mat_cd|siz_cd|C-[0-9]|≥'
  AND cp.note IS DISTINCT FROM (btrim(regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(note, '\s*\([^()]*합가[^()]*(\([^()]*\)[^()]*)*\)', ' / 작업 1건 고정 금액(수량을 곱하지 않음)', 'g'), '^\[siz[^\]]*\]\s*', ''), '\s*\([^()]*(comp흡수|comp_typ|SIZ_[0-9]|MAT_[0-9]|PRD_[0-9]|규칙④|규칙[0-9]|bdl_qty|min_qty|라이브 siz|완제품비\.|완제품가 \.|중첩서브제품|소재묶음|band=|M-[0-9]+정정|행[0-9]|별도 add-on|수량무관 셋업|차원부재|DIRECT매칭|SIZ_PENDING|대표mat|규격단독|상품구분축|후니확인|=comp|추출결함|면당EA)[^()]*(\([^()]*\)[^()]*)*\)', '', 'g'), '\[([^\]]*?)\s*,?\s*mat=MAT_[0-9]+[^\]]*\]', '[\1]', 'g'), '(총제작수량|제작수량|출력매수|수량|장수)≥([0-9]+)', '\1 \2 이상', 'g'), '≥\s*([0-9]+)', '\1 이상', 'g'), '\s{2,}', ' ', 'g')))
  AND (btrim(regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(note, '\s*\([^()]*합가[^()]*(\([^()]*\)[^()]*)*\)', ' / 작업 1건 고정 금액(수량을 곱하지 않음)', 'g'), '^\[siz[^\]]*\]\s*', ''), '\s*\([^()]*(comp흡수|comp_typ|SIZ_[0-9]|MAT_[0-9]|PRD_[0-9]|규칙④|규칙[0-9]|bdl_qty|min_qty|라이브 siz|완제품비\.|완제품가 \.|중첩서브제품|소재묶음|band=|M-[0-9]+정정|행[0-9]|별도 add-on|수량무관 셋업|차원부재|DIRECT매칭|SIZ_PENDING|대표mat|규격단독|상품구분축|후니확인|=comp|추출결함|면당EA)[^()]*(\([^()]*\)[^()]*)*\)', '', 'g'), '\[([^\]]*?)\s*,?\s*mat=MAT_[0-9]+[^\]]*\]', '[\1]', 'g'), '(총제작수량|제작수량|출력매수|수량|장수)≥([0-9]+)', '\1 \2 이상', 'g'), '≥\s*([0-9]+)', '\1 이상', 'g'), '\s{2,}', ' ', 'g'))) !~ 'siz-corrected|comp_typ|PRC_COMPONENT_TYPE|round-2|clr=NULL|별색=공정|옵션=comp흡수|SIZ_[0-9]|MAT_[0-9]|PROC_[0-9]|mat_cd|siz_cd|C-[0-9]|≥';

